### ISSUE TITLE
R Host process stop: unexpected host response, Escape key after browse(), no debugger

### ISSUE THREAD

**Issue by JeongPyoHam** [Microsoft/RTVS#1191]
x<-1:10
browser()
<Escape> (maybe several times...)

Trace.Fail in ProtocolError() is called.

**Comment by int19h** [comment]
The problem is that when `CancelAllAsync` is called, it immediately terminates the ongoing `RunLoop` via cancellation token. But if that loop was an eval loop, the eval response can already be on the way. When that happens, the eval response gets received by the top-level (non-eval) loop, which doesn't know what to do with it. 

Support for async evals, which I'm implementing as part of #541, should take care of this scenario, since that change requires servicing eval responses asynchronously without tying them to any specific loop.
