### ISSUE TITLE
Export feature to MatLab, F#, C#, C++ or Python code

### ISSUE THREAD

**Issue by dngoins** [Microsoft/RTVS#1258]
Have some sort of MathLab or Python wizard that converts MatLab or Python into R or viceversa (maybe an export and import feature)

**Comment by MikhailArkhipov** [comment]
As in #1257, language conversion is very non-trivial and error prone.

**Comment by MikhailArkhipov** [comment]
Language translation is non-trivial and is yet to work even between languages that are close, such as .NET and Java. Another problem is math operations. Each language has different runtime libraries and even exactly same code may product different results due to subtle differences in math rounding or type conversions.
