### ISSUE TITLE
Import Feature to import Matlab, Python or F# code

### ISSUE THREAD

**Issue by dngoins** [Microsoft/RTVS#1259]
Have a wizard to import Matlab, Python, F# code into R.

**Comment by jflam** [comment]
@dngoins by "import" do you mean translating the code (which is an unsolved open problem in computer science) or do you mean being able to reference that code and call it?

**Comment by MikhailArkhipov** [comment]
Language translation is non-trivial and is yet to work even between languages that are close, such as .NET and Java. Another problem is math operations. Each language has different runtime libraries and even exactly same code may product different results due to subtle differences in math rounding or type conversions.
