### ISSUE TITLE
Lines of code treated as response to readline() when running multiline snippet in REPL

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1294]
from user:

In RGUI this script works fine:

h <- 'Hallo'
name <- readline('Name: ')

paste(h, name)

In R-Interactive readline is not doing what it should do.

--- 

in line at a time it works.  if sent to repl as a chunk, the readline doesnt work.

**Comment by int19h** [comment]
This is the fallout of #947, or rather the way we fixed it, by making it so that a multiline code snippet is sent to R line-by-line instead of all at once. Indeed, this was the exact example that was used then to demonstrate why this fix breaks other things.

However, chunking it up is really the only way we can fix the 4096 char limit, unless and until R fixes it on their side.

**Comment by jflam** [comment]
Pavel to file bug with R on this related to #947

**Comment by int19h** [comment]
It looks like the upcoming fix for #1605 will fix this, as well. @AlexanderSher, can you check and close?
