### ISSUE TITLE
RTools Session menu strangeness

### ISSUE THREAD

**Issue by PGS62** [Microsoft/RTVS#1323]
Sometimes I find that the RTools > Session menu has only one item in it: "Execute in Interactive". Shutting down and relaunching Visual Studio brings back the remaining items so that it has seven: "Execute in Interactive" thru "Save Workspace As..." Is this a bug? If there's a good reason for the other items to be unavailable surely they should be greyed out not absent entirely.

**Comment by MikhailArkhipov** [comment]
This happens when R Host process is not running. It does not start by default until R Interactive session is created. The session is created when you either open R file, create or open R project, or explicitly call R Interactive window up via R Tools | Windows | R Interactive.

**Comment by smortaz** [comment]
PGS62 has a point tho... why arent the items grey?

On Wed, Mar 23, 2016 at 12:00 PM, Mikhail Arkhipov <notifications@github.com

**Comment by MikhailArkhipov** [comment]
Default VS command state in invisible. This is because VS has large set of commands and UX recommendation is to hide those that are not applicable to the current state of the IDE. For example, when editor is not open, menu looks like

![image](https://cloud.githubusercontent.com/assets/12820357/13998298/abe48564-f0f3-11e5-97af-c96fd566fdcc.png)

while when it is open it looks like

Default VS command state in invisible. This is because VS has large set of commands and UX recommendation is to hide those that are not applicable to the current state of the IDE. For example, when editor is not open, menu looks like

![image](https://cloud.githubusercontent.com/assets/12820357/13998298/abe48564-f0f3-11e5-97af-c96fd566fdcc.png)

while when it is open it looks like

![Uploading image.png…]()


I.e. not-applicable commands are hidden rather than disabled.
I.e. not-applicable commands are hidden rather than disabled.

**Comment by MikhailArkhipov** [comment]
This, however, can be changed if we choose so

**Comment by smortaz** [comment]
alright, ok.  (weak ok!).

On Wed, Mar 23, 2016 at 12:39 PM, Mikhail Arkhipov <notifications@github.com
