### ISSUE TITLE
Import from csv: Row names "use number" error

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1505]
I'm importing that bikes.csv file, and when I select Row Names=Use number, I get an error:
```
Error in data[[rowvar]] : attempt to select less than one element
```

**Comment by JeongPyoHam** [comment]
Import CSV calls read.csv function, and it could fail with some combinations of input parameter depending on the input file. So, error could be by design and the error should show up in UI. The error shows up in REPL as well, however. That part might be annoying.

To determine if it is legitimate error, could you share the path to bikes.csv?

**Comment by huguesv** [comment]
\\pytools\r\TestData\bikes.csv
