### ISSUE TITLE
VE: row names should be bolded to be consistent with dataframe

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1515]
...

**Comment by MikhailArkhipov** [comment]
Need to check how complex expressions are going to look like. DemiBold may be a compromise. Locals are not bolded.

**Comment by MikhailArkhipov** [comment]
Not entirely convinced...

![image](https://cloud.githubusercontent.com/assets/12820357/14399266/c5f8094a-fd9f-11e5-8430-76f7155b2725.png)

**Comment by int19h** [comment]
I don't think they should be bolded. In VE, rows are just children, there's nothing special about them at all.

**Comment by int19h** [comment]
(and note that all the @-stuff are also children, but are not rows)

**Comment by smortaz** [comment]
Bump up font size instead?

**Comment by MikhailArkhipov** [comment]
Then values are going to be visible smaller in the tall row...

**Comment by MikhailArkhipov** [comment]
![image](https://cloud.githubusercontent.com/assets/12820357/14399634/696a580a-fda3-11e5-9cbe-9f53a93243d3.png)

**Comment by huguesv** [comment]
👎  whatever we have right now is better (non bolded, all same size)

**Comment by MikhailArkhipov** [comment]
Yeah... 👎

**Comment by smortaz** [comment]
Naaa.

**Comment by int19h** [comment]
I don't think it's a big deal. If they want to view it as a grid, Grid View is there. Expanding a data frame directly is basically asking "let me view the internal structure", so there's no reason to do anything special there (because rows aren't really special).

In the future, it would be nice to enable grid nesting in VE, such that expanding a data frame would actually display a small grid with data as a child; with an option to switch to raw structural representation that we currently have. Since grid is a WPF control, it shouldn't be hard to nest it in VE, but we'll need to do multi-instance grids first.

**Comment by MikhailArkhipov** [comment]
Closing for now. We could perhaps shade first column differently but otherwise bolded appearance is not very attractive...
