### ISSUE TITLE
Create Microsoft.R.Interop assembly with helper classes

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1598]

**Comment by int19h** [comment]
I've thought about this for a while, and I think that, as far as high-level primary user API goes, we should try to utilize C# `dynamic` to full extent. Ideally, calling an R function should be as simple as this:
```cs
using static Microsoft.R.Interop.Dynamic;
...
x = R.foo("bar", named: 1)
```
with transparent mapping for all data types - to primitive CLR types where possible (for single-element logical/integer/numeric/complex), and custom types that implement all the applicable standard .NET interfaces otherwise (for vectors, lists, pairlists and environments - with special casing for matrices and data frames).

**Comment by ChrisGro** [comment]
I think this is a great idea.  Many developers are using R.NET ([https://www.nuget.org/packages/R.NET.Community/](url) or RServeCLI; [https://github.com/SurajGupta/RserveCLI2.
](url) for this functionality today.  Presumably, much of the scaffolding / plumbing is already there in RTVS. 

1. While both of these API's are usable (in fact, a godsend that work in the .Net <-> R stack), they do not update very often and can be buggy; it is hard to build production-capable applications using these APIs.

2. An extensive interop capability provides the opportunity for rich applications, be it using Excel / VSTO, WinForms, AspNet, etc.  (although R.dll is known to be problematic with working across app domains, etc).  The old "statconn" COM interface, for example, had some relatively interesting interactivity via Excel [http://www.statconn.com/](url) (which has gone to a commercial license, and most people I have talk to have abandoned). 

The ability to leverage dynamic (similar to what is done with the R.NET F# type provider) would be fantastic.

**Comment by int19h** [comment]
@ChrisGro, I have some questions for you as a potential user.

One big difference between R.NET and what we do is where R runs. R.NET loads R.dll directly into the process; for RTVS, we run it in a separate process.

The out-of-proc approach has some advantages - you're isolated from R crashing or otherwise terminating the process (e.g. `quit()` in R calls `exit()`, which will bring everything down); you can interact with 64-bit R from a 32-bit process; and, since we use websockets for IPC, you can run R remotely.

On the other hand, it adds considerable overhead, exacerbated by the fact that we're using JSON for our protocol.

In fact, the R.NET approach (where it directly exposes R `SEXP`s as .NET wrappers) would be incredibly slow out-of-proc, because you'd have to do a roundtrip every time you are fetching an element from a dataframe, for example. So it would require some form of deferred evaluation, where something like `a.b(42).c["foo"]` is not actually evaluated until you try to use it - at which point the whole thing is sent for evaluation to R, and the result is marshaled back. It would also mean that you would not be working with `SEXP`s directly, but instead get some kind of .NET object wrapping the _data_ instead at the final step (e.g. an `int[]` for an unnamed vector of integers).

Given all this, what would be your preference for such an API? In-proc or out-of-proc?

**Comment by MikhailArkhipov** [comment]
FWIW I think idea is not to make something like R.NET but rather have most of the code in R. I.e. not to expose every possible object to C# and instead provide a way to invoke a function in R that would do lengthy work and return the data. I guess similar to a Web service call.

**Comment by int19h** [comment]
Sure - R.NET already covers the low-level direct access angle. But even for the higher level approach, it could be done in-proc or out-of-proc (i.e. using either R.NET as a basis, or our R host and its client), and both approaches have their advantages and disadvantages.

**Comment by ChrisGro** [comment]
@MikhailArkhipov "Recreating" R in .Net seems to be a massive undertaking.  But making an API that allows one to "push/eval/pull" using sensible type conversion mechanics seems to be both do-able and a high value add to people that work in this stack (many of us do this every day with R.Net or RServeCLI).   I think this use case would suggest an out-of-process implementation as "good enough".   

You're right to point out the complexity and performance trade-offs associated with choosing in / out of process.  I would think that, to support what is likely the most common case, you would work out of process.  I think the most common workflow is something like:

1. In the .Net environment, you are collecting data / parameters; your data is in native .Net types. 
2. That data is then marshalled to R; you invoke some R function(s) on that data.  R will create an output (dataframe, list, primitive vector, etc).
3. .You then pull that data from R, marshalling back to .Net types. 

In a hypothetical example: 

// Some double array 
double[,] arr = new double[,]{ ....}

// Push to R 
R.SetMatrix(arr,"my.matrix");

// Eval 
R.Eval("my.pca <-prcomp(my.matrix,center = TRUE,scale. = TRUE) 

// Pull 
double[,] rotation_matrix = R.GetMatrix("my.pca$rotation")

The advantage of in-process is, of course, performance from the shared memory space and statefulness.  Out of process loses statefulness, and has the marshaling performance overhead, but I think would support most use cases and is best suited for a services-based orientation (be it remoting, Web Services, WCF) etc.  

From an API design perspective, one could think of a RNative layer that works in-process and works with SEXP abstractions and the like, and an RRemote layer that sits on top of that and provides .Net type conversion functionality and "get" and "set" behavior.   Presumably, a user could choose to operate at whatever level they needed. However, I think that 99% of the time, most users would be fine operating out of process with the RRemote layer that just let you "set", "get" and "eval". This is how I use both R.NET and RServeCLI today (we have an extensive wrapper class that allows us to push time series as xts objects, IEnumerable<T> as dataframes, double[,] as matrix, etc.; this class also allows us to marshal back most of those objects in the other direction composing them from the more primitive R types)   

I also agree with your point about not exposing every R object in a C# analog.  Users are fine with just need to push data, write r code to work on that data, and then retrieve output (in .Net friendly types, like int[], double[], double[,], string[], etc.).  (Higher order objects like dataframes,lists, etc. are more complex, but are just compositions of the underlying R primitive types - but it's unclear how you would want to represent them in .Net; a DataTable jumps out as one option).    

Hope this helps.  Happy to talk more.
