### ISSUE TITLE
Support code folding and sections

### ISSUE THREAD

**Issue by AMarthallerMS** [Microsoft/RTVS#1610]
RStudio supports translating certain comments into code folding sections.
https://support.rstudio.com/hc/en-us/articles/200484568-Code-Folding-and-Sections

It would be great if the VS IDE also understood these hints.

**Comment by MikhailArkhipov** [comment]
Similar to C# ```#region```

**Comment by fabriciovasselai** [comment]
That is one of the features I have been advocating the most since the first non-public release. It helps me a lot to organize my code when using VS for C# or even for C++ even it's a little diffrent there. It would be great to have such a feature for RTools too.

I would like to call the attention to a nice behavior of `#regions` in C#: one can even comment the region section, which ends up working as a "region title" for when code is folded. Would be great to have that as well.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/4c5229b7cc2a65de7eacf1dc77f3c27fc9f4f9e8
