### ISSUE TITLE
Support Add Reference

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1612]

**Comment by MikhailArkhipov** [comment]
Which translates to 'which packages to load automatically when application starts'. Will need special UI dialog since we probably can't reuse VS Add Reference.

**Comment by int19h** [comment]
Add Reference usually implies references to either files or other projects in the solution - I don't think package autoloading is a good match here (meaning that it's a good thing to have in general, but it'd be better off as a list labeled such in project properties etc).

At the most basic level, we should have project-to-project references just so that MSBuild dependency tracking can be used (i.e. when R project relies on something produced by building another project) - without any special support in the IDE.

Beyond that, we can see if there's any sort of interop that can be at play here. For example, R has a [facility to call exported functions from a DLL](https://stat.ethz.ch/R-manual/R-devel/library/base/html/dynload.html) (without having to turn it into a package). We could hook that up such that, if you add reference to a DLL or a C++ project, it automatically gets dyn-loaded on F5.

**Comment by MikhailArkhipov** [comment]
Doesn't need to be called 'Add Reference' as it is indeed a different concept. However, there were requests for this on RS feedback and SO. Seem to fit into the F5/App scenario.

**Comment by int19h** [comment]
Let's file a separate item for that, and leave this one for development of the user story around Add Reference specifically.

**Comment by MikhailArkhipov** [comment]
Needs spec
