### ISSUE TITLE
Working directory selector shows garbling for non-ascii characters

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1661]
After selecting path with Japanese characters, working directory selector shows garbling.
This issue does not occur for all Japanese characters, but at least occur when selecting a folder named "おしごと". 

![selecting](https://cloud.githubusercontent.com/assets/3863577/14702928/297d8830-07e8-11e6-8091-c1865689a958.PNG)
![garbling](https://cloud.githubusercontent.com/assets/3863577/14702933/2bcfebaa-07e8-11e6-811b-a43831041c06.PNG)

**Comment by int19h** [comment]
It's because we fetch the result of `getwd()` to fill the text in that textbox after the directory changes by any means (including the selector), and it uses a normal eval that doesn't play well in Unicode. Need to change `SetWorkingDirectory` to use `REvaluationKind.Json` - that will marshal the string literal properly.

**Comment by MikhailArkhipov** [comment]
```
setwd("~/Documents/фыва")
Error in setwd("~/Documents/<U+0444><U+044B><U+0432><U+0430>") : 
```

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/8686cc5e5132f2336df3950b9d1765abdc44c6e5
