### ISSUE TITLE
Provide auto-positioning of curly braces when the auto-formatting is off

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1689]
If I don't control indentation, place of a closing curly brace is wrong when the auto-formatting is off.
```
if (a == 2){
	print(a)
	} else {
print(2)
		}
```

**Comment by MikhailArkhipov** [comment]
Placement of curly braces is actually automatic formatting since curly position is automatically changed. 

There is also smart and block indent modes which define where caret is placed when user hits Enter at the end of the line. In 'smart indent' editor places caret depending on context so it will be indented one level deeper after {. In 'block indent' indent is simply equal indentation of the previous line, no scope analysis is performed.

So generally editor behaves as expected. I guess one may desire 'light auto-format' that C# performs where editor does not format the code but only adjusts position of }. In R ^K^D will format code typed so far and fix indentations.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/468732e509cab0e9ff2a8d509e9afc2059d2174d
