### ISSUE TITLE
Allow use of R-devel; warn less about incompatible version numbers

### ISSUE THREAD

**Issue by richierocks** [Microsoft/RTVS#1727]
I tried to use RTVS with the latest R-devel, which has version 3.4.0.  During installation I got a warning pop-up saying that this release only supports the 3.2.* and 3.3.* versions of R.  The ability to work with R-devel is important, particularly for submitting packages to CRAN.  I don't know if RTVS genuinely doesn't support R-devel or whether the warning is too restrictive, but either way something needs fixing.

For reference, I did have R-3.2.5 installed on my machine, so the logic for how RTVS should find a suitable R version might need revisiting.

Also, I was warned 3 more times that R-3.4.0 wasn't supported while starting Visual Studio to go and change the settings to a different version, each time opening a new browser tab to take me to the MRO download page.  Once would be sufficient.

**Comment by MikhailArkhipov** [comment]
Which version RTVS finds depends on particular R setup. Automatic lookup first looks into registry and if nothing suitable is found tries to look into well known locations in the Program Files folder. However, if path was previously set in VS options, no search is performed. So installation of additional R version does not cause RTVS to re-scan. 

It is possible to get multiple messages since different components perform checks if the option stored in VS settings is suitable. 0.3 was not tested with 3.4 so 3.4 was not enabled. In the future, we probably will remove upper cap. It actually exists since some older R versions claim higher versions (old RRO claims it is 8.0 in registry while actually it is R 3.1.*)

**Comment by MikhailArkhipov** [comment]
Revved up 0.4 to 3.9 max optimistically

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/2ac3848c8cd29014a9aeca12f0d3855e26f04bd8
