### ISSUE TITLE
Make new instance of data grid appear tabbed with the most recent grid

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1799]
Rather than with the default Solution Explorer per specified attribute. https://msdn.microsoft.com/en-us/library/h41w1yxb.aspx may help.

**Comment by smortaz** [comment]
+1

**Comment by int19h** [comment]
Should we just start showing them in the editor tabwell, like RS does?

**Comment by smortaz** [comment]
Why?

**Comment by int19h** [comment]
1. Because RS does it.
2. Because there's way more space there, so grids will display more data than when they're stuck in a corner.
3. Because having new tabs appear there is something that users are more accustomed to - tool windows are usually more static in their arrangement.

**Comment by smortaz** [comment]
1. Not crazy about that argument. For me I dislike my editor to the side
only covered when there is another place to display it

2. I usually divide half-and-half so they're about equal for me

3. If it appears in the lower right quadrant where I usually have my grid,
I will surely notice it, especially since I expected it to go there…

It's also possible they did it because of window management limitations.
Either way I like it to appear wherever my last grid was placed, which is
usually lower right

**Comment by MikhailArkhipov** [comment]
It should be getting docked with the most recent one now.
