### ISSUE TITLE
`else` at the end of a line in R Interactive window

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#1867]
This executes fine but generates the red squiggly.

![image](https://cloud.githubusercontent.com/assets/3840081/15909343/c1d9490e-2d7a-11e6-9430-502a5cb9380a.png)

To repro this:
```
>x <- TRUE  #Hit return
>y <- if(x) #Hit return
+ {100} else #Hit return
+ {-100}
>
``` 

Note: This is fine.
![image](https://cloud.githubusercontent.com/assets/3840081/15909720/795fe4a6-2d7c-11e6-8cbc-b532ed840f19.png)

**Comment by MikhailArkhipov** [comment]
As I suspected: + splits buffer and what we are actually parsing is 

```{100} else```

Parser doesn't see opening if since it is now inert area before the line break. This is exactly why we have option to switch off syntax check in REPL since it does not always work reliably due to the REPL buffer graph structure.

**Comment by MikhailArkhipov** [comment]
So little we can do here.

**Comment by int19h** [comment]
Can we string up all the buffers together so we can parse them as a single entity?

@DinoV, do you remember how Python REPL deals with this problem (if it does?). E.g. something like:
```py
if True \
: pass
```
