### ISSUE TITLE
Some code pages shown in the code page drop down are not honored

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#1901]
Repro steps:
Set Code Page in R Tools Options to ISCII Kannada

```
> Sys.getlocale("LC_CTYPE")
[1] "English_United States.437"
Warning messages:
1: In Sys.setlocale("LC_CTYPE", ".57008") :
  OS reports request to set locale to ".57008" cannot be honored
```

**Comment by MikhailArkhipov** [comment]
Yep, we should .NET list while R actually uses list from C runtime or something that is not entirely documented. So our list is basically optimistic.

**Comment by int19h** [comment]
We assumed that if it has a codepage, it's supported, basically. But apparently MinGW (well, msvcrt.dll) doesn't know about many encodings, not just UTF-8. It might be worth seeing if we can get access to that code, and just make it a hardcoded list, since it's not a component that is going to have new stuff added to it.

**Comment by MikhailArkhipov** [comment]
If it just one or two exotic ones I wouldn't bother. I remember trying common/popular ones and they worked.

**Comment by int19h** [comment]
It looks like it's all the various ISCII varieties, at the very least.

**Comment by MikhailArkhipov** [comment]
OK, I will filter these ones for now

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/2672327dadc2f80501ae313d688a7b2cd7e09468
