### ISSUE TITLE
Help window is immediately hidden at a breakpoint.

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#2020]
When calling help via ? command in the interactive at a breakpoint, help window (docking mode) is shown, but the interactive is activated immediately again.
I think this may be related with  #1902.

**Comment by MikhailArkhipov** [comment]
Normally help window is not activated. If you have it on auto-hide, it will indeed show and then disappear since it does not gain focus. You can pin it manually.

**Comment by Marchen** [comment]
Usually, I'm using help window like following arrangement.

![help](https://cloud.githubusercontent.com/assets/3863577/16433424/2998b9b2-3dc5-11e6-9b19-31dbc257fae6.PNG)

With this arrangement, normally help window is activated if it's not at a breakpoint, but at a breakpoint, interactive is activated again immediately after help window was activated.

**Comment by int19h** [comment]
This is due to our hackaround for editor stealing focus from REPL when hitting a breakpoint (we steal it back and give it to the REPL, which is _usually_ the right thing, but wrong in this particular case).

The same problem will also appear with `plot()`, if you dock the plot window alongside the REPL.

**Comment by int19h** [comment]
It looks like the proper fix would be for us to keep track of the last window that had focus, among windows of interest (which is help, plot, and grid right now; but generally, anything that can be activated by means of evaluating R code in the REPL). When editor steals focus on debug break, we should steal it back to the last window on that list that had it.

**Comment by Marchen** [comment]
Yes, `plot()` also caused similar behavior.

**Comment by MikhailArkhipov** [comment]
It is not breakpoint. If window is not pinned, it is displayed but since it doesn't gain focus, VS pulls it back. We theoretically could auto-pin it, but that is not considered a good practice...

**Comment by MikhailArkhipov** [comment]
See https://github.com/Microsoft/RTVS/issues/1266

**Comment by Marchen** [comment]
For my case, I pinned the help window (like the image above), but the help window go away immediately.

**Comment by int19h** [comment]
It is a breakpoint (or equivalent) - note the `Browse[1]>` prompt in the REPL. What happens here is just a more complicated version of #1938:

1. Debugger is paused at a breakpoint (or after a step etc).
1. `?foo` is executed in the REPL at the Browse> prompt.
1. VS goes from break state to running state.
1. R begins executing code.
1. `?` causes Help window to appear.
1. R ends executing code.
1. VS goes from running state to break state; editor steals focus from Help.
1. We notice that we lost focus due to state change, and that REPL had focus before, so we give REPL focus.

That last step is a problem. The way we worked around current VS behavior assumes that between user pressing Enter in the REPL, and VS debugger stealing focus once execution completes, no new window gets focus; but it's not true in case of `?`, `plot()` and `View()`.

**Comment by MikhailArkhipov** [comment]
Appears to work OK in master
