### ISSUE TITLE
Auto-formatting add extra space at line break

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#2025]
When I hit ENTER between `something,` and `family` of the following code,
```R
glm(
	y ~ x, data = something,family = Gamma)
```

Auto-formatting puts extra space before `family`.
```R
glm(
	y ~ x, data = something,
	 family = Gamma)
```

If I undo, there is a step between the two:
```R
glm(
	y ~ x, data = something, family = Gamma)
```

**Comment by MikhailArkhipov** [comment]
This is fairly normal in auto-format cases as it sometimes yields two undo steps. It is same as in C#, for example. The reason is that first editor introduces line break and then calls for formatting. VS does have compound undo actions where multiple changes can be wrapped in a single undo, but in this particular case it is hard to determine when to open such action since particular keystroke may or may not be followed by additional action.

**Comment by Marchen** [comment]
Thanks for the explanation. I understood undo steps of auto-format in VS. But my point was that maybe because of order of sequential actions of auto-format (hit RETURN -> insert a space -> put line break and adjust indent), an extra space was put on the beginning of new line. In the example above, indent of the line start with `y ~ x` consists of a TAB, but that of the line start with `family` consists of a TAB and SPACE.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/7235095f9d8517e3b869ea588d95700b8ac8fdf3
