### ISSUE TITLE
Document potential AV software issues

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2027]
Or give user a message that AV software may be affecting logger.

```
These symptoms strongly remind me of some overly aggressive antivirus software – some of them will watch the file system, and as soon as a new file appears, will open it for exclusive access to run a scan on it. If the application does rapid open/write/close cycles on the same file (as is the case with plots when you resize one, I believe), it may try to open the file for the second time while AV is still running the scan. This has been a major source of problems for VS in general historically.
```

![23](https://cloud.githubusercontent.com/assets/12820357/16466007/5f0985c8-3df6-11e6-8882-bd1dafb7d7ed.png)

**Comment by int19h** [comment]
Also applies to plots. Really, applies to anything that can potentially write a file to disk, close it, and then open it very shortly afterwards.

For what it's worth, VS itself has suffered from similar issues (often breaks F5, because the newly built .exe cannot be copied from obj to bin), and ended up just doc'ing it. So at this point there's already an established understanding that dev tools do require disabling (or at least dialing down, via exclusions) your antivirus.

**Comment by MikhailArkhipov** [comment]
Since this affects many areas, we can't really fix it completely. We'll doc it then as VS did.

**Comment by MikhailArkhipov** [comment]
Over to https://github.com/Microsoft/RTVS-docs/issues/51
