### ISSUE TITLE
plotly::plot_ly does not work in 0.4 - Active Content Blocked

### ISSUE THREAD

**Issue by AMarthallerMS** [Microsoft/RTVS#2056]
Sample:
require(plotly)
df <- data.frame(1:10, 1:10)
names(df) <- c("X", "Y")
plot_ly(df, x = X, y = Y)

There are a lot of libraries using the htmlwidgets package. We need 1st class support for this the same as ggplot. http://www.htmlwidgets.org

**Comment by huguesv** [comment]
There's an option to control whether we open web pages in the internal browser (Internet Explorer) or external (whatever your system browser is).

![image](https://cloud.githubusercontent.com/assets/1696845/16740889/d73722fe-4755-11e6-9e19-182ca18ec6b8.png)

We may have to rename that, since it's not exclusive to Shiny.  Anyway, as long as your system browser isn't IE, that should work fine.

A long term solution is to host a better browser than Internet Explorer. That's currently in our 'Future' milestone.

https://github.com/Microsoft/RTVS/issues/879

BTW I tried to turn off the block active content feature, or temporarily enable it, but that didn't help, it still rendered nothing.

**Comment by AMarthallerMS** [comment]
That does fix the issue... I agree that a rename is probably in order since I skipped over this setting when poking around. Thanks!

**Comment by MikhailArkhipov** [comment]
Which port range does plotly use? We may separate it into another option

**Comment by AMarthallerMS** [comment]
I don't think it uses a port. The htmlwidgets framework writes a file to disk and opens it.
file:///C:/Users/AMarthallerMS/AppData/Local/Temp/Rtmp6zDOFA/viewhtml236c1c141883/index.html

Any settings for that would likely not be Plotly specific, but htmlwidgets specific.

You can specify the port in Shiny BTW. If you are using port to select options that seems quite fragile.
