### ISSUE TITLE
Handle project loading when R is disconnected

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2093]
- Show yellow message bar in Solution Explorer (or find any other way to show notification)
- Disable automatic RData loading for remote scenarios for local files

**Comment by MikhailArkhipov** [comment]
Project opens fine. Editor opens. REPL behavior is s expected, getting appropriate error message. Need to handle intellisense better since it is attempting to start the session and typing is slow. Although not entirely legal case, but some may need/want to edit R without actually having the connection up. Obviously, intellisense will work only partially.

**Comment by MikhailArkhipov** [comment]
#2251 more or less takes care of found issues. Otherwise there is no feature work.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/d132ef920675674d6ff2a8c7649fb3fdde98402f
