### ISSUE TITLE
Export to CSV should not be available on types that cannot be coerced to data.frames 

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2114]
`m` should not have the export to Excel button on it.
![image](https://cloud.githubusercontent.com/assets/3840081/17077142/52137dd8-507a-11e6-8b25-f0c8d133d156.png)

When I click the button, write.table fails to coerce `m` to `data.frame`. 
```
Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ""lm"" to a data.frame
```  

This later causes a crash in RTVS when we attempt save the exported content (which is NULL) to the file.

**Comment by MikhailArkhipov** [comment]
There was a bug on this a while ago. We basically don't know if type can be converted so we show the button optimistically. It is too expensive to check for each entry. We certainly should not crash though.

**Comment by int19h** [comment]
In most cases, we can actually convert - we just need to strip the classes first, so that it's just a plain vector. The trick is figuring out which classes to strip, and which to keep (we don't want to strip everything, since that'd mangle dataframes, for example).

**Comment by int19h** [comment]
Actually, it looks like we can have a reliable check, or a reliable list of classes to strip.

The offending function here is `as.data.frame`, but it's actually an S3 method. It's defined for lists (`as.data.frame.list`), vectors (`as.data.frame.vector`) etc. As any method, it also has a default implementation, `as.data.frame.default` - which just throws.

So, something is convertible to a data frame if, and only if, there is an S3 method implementation for one of its classes. And we can get the list of all method implementations like so:
```r
methods(as.data.frame)
```

Another option is to call `getS3method` for every class that the object has (usually there will be only one, rarely 2 or 3, so it's fast enough), and see what we get back. That way we don't even have to parse method names to figure out classes.

**Comment by MikhailArkhipov** [comment]
Need to measure perf on this since user does can have 10s of entries in VE. I also remember that grid code in R didn't covert all objects to DF and handled 1D and matrices differently. Might have changed since...

**Comment by int19h** [comment]
The grid code didn't convert initially, then was changed to convert, then was changed to not convert again (because conversion is sometimes lossy, and can be very expensive). But export code is different from grid code, and currently converts always. It's actually implicit, because when you invoke `write.table`, it will convert inside.

Perf-wise I think this should be fine. The expensive check would be trying to convert manually via `as.data.frame` and catching errors - that would be very costly for large matrices and such. But `class` is very cheap, since it's just an attribute - and we fetch it already. OTOH, getting a list of implementations for a given generic method and class should also be pretty cheap, since it's just a bunch of ID lookups. We can constrain further by adding some extra checks (e.g. don't even try it on 1-element vectors, functions etc).
