### ISSUE TITLE
Allow xts (and other object types) to be transferred to Excel

### ISSUE THREAD

**Issue by ivannp** [Microsoft/RTVS#2155]
Hello,

In the Variable Explorer window, currently only data frames can be opened in Excel. There are other R types, which are widely used, and are quite similar to a data frame. Time series objects (package xts) come to mind as an example. Could these be supported as well?

Thanks in advance

**Comment by int19h** [comment]
Currently, we use `write.csv` to produce the files to then open in Excel - do those types support that?

**Comment by ivannp** [comment]
Yes they do. The output can be tweaked using write.csv parameters as well. Here is one way to write a csv out:

require(quantmod)
s = getSymbols("SPY", auto.assign=F)
write.csv(s, file = "s.csv", quote=F, row.names=F)

**Comment by int19h** [comment]
@karthiknadig, I think your recent change to check for `as.data.frame` is 99% of the solution here. The only potential problem is that we also check for a bunch of other stuff before showing the Excel button:

https://github.com/Microsoft/RTVS/blob/267f5525ff62611756cd74ac46d627b42ca7f9e4/src/Package/Impl/DataInspect/VariableViewModel.cs#L65

It seems that the only check we should really be making there is `CanCoerceToDataFrame`, and drop the rest. Then we'll just show the button for anything that `as.data.frame` (and hence `write.csv`) can handle, even if our data grid viewer doesn't support it. Maybe also have a length check, since exporting 0- and 1-length vectors is kinda pointless.
