### ISSUE TITLE
The R timestamp() function causes R Interactive console to crash.

### ISSUE THREAD

**Issue by sfweller** [Microsoft/RTVS#2166]
Here is a reproduce of the issue in RTVS. Note that this crash does not happen in the MRS Rgui console.

R version 3.2.2 (2015-08-14) -- "Fire Safety"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Microsoft R Open 3.2.2
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2016 Microsoft Corporation

Loading Microsoft R Client packages, version1.0.0. 
Microsoft R Client limits some functions to available memory.
See: https://msdn.microsoft.com/en-us/microsoft-r-client-windows for information
about additional features.

Type 'readme()' for release notes, privacy() for privacy policy, or
'RevoLicense()' for licensing information.

Using the Intel MKL for parallel mathematical computing(using 4 cores).
Default CRAN mirror snapshot taken on 2015-11-30.
See: https://mran.microsoft.com/.
> find("timestamp")
[1] "package:RevoMods" "package:utils"   
> utils::timestamp()
R Host process is stopped. Click Reset to start a new one.

Stephen Weller
Microsoft R Product Team

**Comment by int19h** [comment]
Interestingly, it also crashes RStudio in the same exact way. Also, here's some discussion of this:

https://support.rstudio.com/hc/en-us/community/posts/200655683-Error-in-history-function-not-supported-in-RStudio

with a rather unfortunate conclusion:

"We actually had to remove support for history() and timestamp() in RStudio on all Windows platforms. This is because of a change in R that we cannot get around at this time."

**Comment by int19h** [comment]
Another aspect of this is that the version that's from the "RevoMods" package (which is specific to MRS/MRC) seems to be plainly broken - it's a slightly modified version of the original `utils::timestamp`, including this line that calls into the C implementation:
```r
.External2(C_addhistory, stamp)
```
which doesn't work, because the C function that it's calling is in a different package (`utils`). So when you invoke it, you get an error message:
```
> timestamp()
Error in timestamp() : object 'C_addhistory' not found
```
This one happens regardless of the environment - RStudio, RGui and RTerm all do this. So looks like an MRS bug.

**Comment by sfweller** [comment]
Thanks for investigating this Pavel. I originally thought that this may  be a problem with RTVS - I will see if we can fix this in RevoMods.

Stephen Weller
