### ISSUE TITLE
Broker does not terminate when test is over

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2202]
Run a single test that starts the broker, such as VariableExplorerTest.SimpleDataTest. The broker process starts but does not terminate when test is over. Attempt to run another test fails b/c build in VS fails.

![image](https://cloud.githubusercontent.com/assets/12820357/17984793/bed0bc80-6ac7-11e6-8776-6e2ece83c5f6.png)

![image](https://cloud.githubusercontent.com/assets/12820357/17984731/62645b00-6ac7-11e6-8a29-ac0784ff3071.png)

**Comment by int19h** [comment]
I suspect that this is happening for some tests but not the others. For the broker to be properly shut down, the test class must invoke `Dispose` on its `RHostBrokerConnector` instance. If it doesn't do so, the broker will hang around. So whenever you hit this, list the tests for which it's happening.

(The usual watchdog protection for shutting the host down automatically doesn't trigger, because it checks whether the parent process is still running - and the parent process in that case is VS test runner execution process, which is reused between test runs).

**Comment by int19h** [comment]
For this particular test (and any other test that uses `VsRHostScript`), the broker isn't created directly, but is rather requested via `IRInteractiveWorkflowProvider`:
```cs
                VsAppShell.Current.ExportProvider.GetExportedValue<IRSessionProvider>(),
                VsAppShell.Current.ExportProvider.GetExportedValue<IRInteractiveWorkflowProvider>().GetOrCreate().BrokerConnector,
```
So it's the provider that's responsible for disposing it. Which it will do if it's disposed itself, but this never happens in practice. I'm not sure what exactly is going wrong there - the provider is obtained via MEF, and my understanding is that MEF is responsible for disposing components that are disposable, when container is shutting down. But in this case, `Dispose` is simply never called. @AlexanderSher, are any of these assumptions wrong?

**Comment by AlexanderSher** [comment]
> I'm not sure what exactly is going wrong there - the provider is obtained via MEF, and my understanding is that MEF is responsible for disposing components that are disposable, when container is shutting down. 
The problem here is that there is no test fixture - MEF is initialized in `TestVsAppShell` singleton, so with these tests broker instance is shared between tests.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/16bbfb33f3c03917ba44003ed507f46f3920cfac
