### ISSUE TITLE
Connection management 

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2222]
IVsUIHierarchyWindow https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivsuihierarchywindow.aspx

This way we could add `R Servers` node and later add `R Servers` subnode to the Azure root

![image](https://cloud.githubusercontent.com/assets/12820357/17989779/b2402aba-6ae4-11e6-8be5-ab830f03b654.png)

**Comment by MikhailArkhipov** [comment]
Possible alternative

![image](https://cloud.githubusercontent.com/assets/12820357/17990162/400638fa-6ae8-11e6-8629-1c1cf00b72ab.png)

**Comment by AlexanderSher** [comment]
I like the way they do add/edit without modal dialogs.
But why do you want to have tree structure? To separate local connections from remote?

**Comment by int19h** [comment]
I think the idea is to stick it into some existing dialog under a separate node. So, like Azure has its own node in Server Explorer, we could have one titled "R Servers", for example, and then connections under it. 

Also, if we add support for DeployR batch submissions in the future, that would also be a logical place for that. And similar stuff like Spark etc.

**Comment by AlexanderSher** [comment]
The problem with sticking to the server explorer is that we'll have to deal with `IVsUIHierarchy` and also we will be very limited to the UI features. I would like to be able to add buttons, drop-downs and any other custom UI elements to the list items. I'd rather have buttons like "connect", "edit" and "delete" on the item itself instead of just the context menu.
On the other hand, it's not a big deal to strip design from the Team Explorer (which is a WPF control).

**Comment by int19h** [comment]
Yeah, that's also my concern with Server Explorer. It's worth noting that VS Azure Tools have historically integrated into Server Explorer (and they still have nodes there), but at some point they got sufficiently frustrated with its limitations that they've made their own separate Cloud Explorer tool window:

https://visualstudiogallery.msdn.microsoft.com/84e83a7c-9606-4f9f-83dd-0f6182f13add

Perhaps we could reuse that code, too?

On the other hand, Server Explorer is the most logical place to find that kind of stuff, from perspective of existing VS user. UI-wise, we could only display the nodes there, and use Properties window to edit name, URL and other stuff (and we can have dropdowns, buttons and any kind of custom UI there easily). It's not quite as convenient for the user due to having two different windows, but then again it would follow the VS UX conventions - Solution Explorer does the same for its nodes, and so on.

**Comment by MikhailArkhipov** [comment]
Consider balancing with time available. Either approach is fine as long as it won't take weeks to implement. I am not a big fan of Server Explorer either, but it may be simplest approach. We only need one node with entries, there is a toolbar for buttons where we can add New/Delete/Edit. Modal dialog prevents user from clicking around when async operation may be in progress reducing bug surface.
We may use properties window but modal dialog is also fine - Connect to Database... uses modal dialog with 'Test Connection' and only uses properties window as readonly display. Speaking of properties window - we could use it to display the connection status.

Reviews for cloud explorer is 2 stars so caveat emptor.

It's going to be a while until we need more that one or two nodes with a list of connections.

**Comment by MikhailArkhipov** [comment]
#2230 for the Server Explorer part. Still need proper connection management, disconnect on delete, prevent deleting at least one local interpreter, better modal dialog for creation of connections (if it is always http maybe just machine name and the port fields), provide connection data/statistics etc.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/f58f1a115e9a17547093899236a0887d806cf578
