### ISSUE TITLE
Should RTVS quit the R process when the REPL window is closed?

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#2275]
Say I close my R project and open a C# project (or any other language). The REPL window remains open. My C# project is unrelated to R, so I close the REPL. However, R itself is still running in the background, which I wasn't expecting.

Should RTVS close R when the REPL window is closed?

Going one step further, should the REPL window (and the R process) be closed automatically when closing an R project?

**Comment by MikhailArkhipov** [comment]
Normally no. Closing tool window in VS only hides it. One can temporary close Solution Explorer but that doesn't mean project is closed. Also, since R doesn't require project closing project doesn't mean the session is over.

However, there is a point that R is still running somewhere and may not be needed. Perhaps it is worth providing 'Terminate R' command which will be actually closing the session. This also comes useful with remote connections.

**Comment by Hong-Revo** [comment]
Maybe an option "terminate R process when REPL window is closed" would work too.

**Comment by MikhailArkhipov** [comment]
Added 'Terminate R' command.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/36b29e31163b93168fcd589102cb12789bc4b4f7
