### ISSUE TITLE
Backslashes in the SQL connection string content need to be escaped

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2420]
`\\`

**Comment by huguesv** [comment]
If in general it's up to the user to escape the backslash for a regular setting (when typing it in the settings UI), then we probably want to do the escaping in `AddDbConnectionCommand.Handle`, because the command is adding the setting on behalf of the user.
Once it's added, loading and saving settings don't unescape/escape the values, and SQL isn't treated specially.

**Comment by huguesv** [comment]
I'm changing my mind.  It should be escaped/unescaped when it's serialized/deserialized in settings.R (for all types of settings).  This matches what C# does with settings files, and resx files, ie. it's not up to the user to escape the values entered in the UI.

With my original plan, I was ending having to escape/unescape the settings values in different places where the SQL string was retrieved/updated, and that was getting too far away from where the settings.R file handling (too easy to miss).

**Comment by huguesv** [comment]
Fixed in https://github.com/Microsoft/RTVS/pull/2449
