### ISSUE TITLE
Odd message from plots

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2448]
Suddenly got this after connecting to remote
![image](https://cloud.githubusercontent.com/assets/12820357/19171121/0bc3548e-8bd0-11e6-838f-976a6bed7352.png)

**Comment by int19h** [comment]
This is because it's reconnecting to an existing live session, and the dummy package used to store plotting related stuff gets duplicated. Since we decided to drop reconnection for RTM, this is trivially fixed by disabling the reconnect feature.

I was planning to do it as part of my session-save-on-exit work, but if we don't want to wait, it's trivially done by making this variable always false:

https://github.com/Microsoft/RTVS/blob/38ebb467cc4944ca29eab36ddf8c135c20889593/src/Host/Client/Impl/Host/BrokerClient.cs#L92

**Comment by MikhailArkhipov** [comment]
Close it ?

**Comment by int19h** [comment]
Closing for now since it's no longer applicable. But we'll need to revive this item when we fully implement true reconnection.
