### ISSUE TITLE
Formating: function body without {} is indented wrong

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2469]
Before:

``` r
open_url <- function(url)
    rtvs:::send_notification('!WebBrowser', url)
```

After:

``` r
open_url <- function(url)
rtvs:::send_notification('!WebBrowser', url)
```

**Comment by Hong-Revo** [comment]
I don't see why the 'after' is wrong? That's how I would format it....

**Comment by Hong-Revo** [comment]
Also, R's built-in syntax formatter (`dput`) prints a one-line function without an indent:

```
> foo <- function(x) f(x)
> dput(foo)
function (x) 
f(x)
```

Not that `dput` is necessarily best practice, though.

**Comment by MikhailArkhipov** [comment]
It is a good question :-). C# does indent. There actual issue here is preservation of user indent. If you indent it, then that's the way you wanted it. Generally speaking there is a balance in formatters between fidelity and performance. Formatters working off parse tree (AST) provide the best fidelity and capabilities but they are also slow for automating formatting as you type. Formatters working off token stream are fast, but they also have less information about the overall structure and semantics.

**Comment by MikhailArkhipov** [comment]
Basically same as #2641
