### ISSUE TITLE
Can't source files in a remote session when debugger is attached 

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2495]
```
x <- 1
y <- 2
z <- 3
```

set bp somewhere
Attach debugger
Try sourcing file

![image](https://cloud.githubusercontent.com/assets/12820357/19366688/fca880fa-914c-11e6-9e20-4d1fe1c689cf.png)

**Comment by int19h** [comment]
This is currently by design per #2033. We transfer locals files to remote on F5 and "Source Selected Files" in the project, because the project defines the remote path to which the files go. But if you just source a random file, we don't know where it's supposed to be mapped to on the remote system, so no mapping is done.

One possible approach here would be to check if the sourced file belongs to any open project, and if so, then treat it same as "Source Selected Files". @jflam, does that make sense?

If we want to make this work for any random sourced file, we need to come up with a consistent _zero-configuration_ way to map local paths to remote.

**Comment by MikhailArkhipov** [comment]
We can try and re-map relative to the user documents folder so same path local and remote. If path is not under Documents (user works off some random local folder) then re-map (example C:\Foo\Bar) to [remote]Documents[C\Foo\Bar]

**Comment by int19h** [comment]
That would not be consistent with what we do for files in the project - i.e. sourcing the file from the editor, and sourcing it from the project, would put them into different places. I think whatever is done here, it should be consistent throughout.

We do have a default mapping that we set for new projects. I'm thinking that, perhaps, we could treat files not coming from a project as if they belonged to a project in the same folder the file is in, and then use that default mapping? If user wants to change, then they can create a project explicitly and configure mapping in properties, and source would pick it up.
