### ISSUE TITLE
Remote: rtvs::: is not autocompleting

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2507]
When I want to fetch a remote file and I type "rtvs:::" I'm expecting to see command completion, but I don't. The command works fine, however and retrieves the file successfully.

rtvs:::fetch_file("foo.csv")

**Comment by int19h** [comment]
It seems like there's some general problem with `::` and `:::` Intellisense. I don't get a list when I just type those in the REPL, and Ctrl+Space gives a list of everything available globally, rather than just package/namespace members.

**Comment by MikhailArkhipov** [comment]
`utils::` and `RODBC::` work fine

![image](https://cloud.githubusercontent.com/assets/12820357/19448090/2378978c-9455-11e6-9724-e6c0d6388b8e.png)

![image](https://cloud.githubusercontent.com/assets/12820357/19448102/3650d1f8-9455-11e6-9963-c6be60196ad7.png)

It appears that 'rtvs' is not really a package since it does not appear in the list of loaded or installed packages and hence completion does not see it.

![image](https://cloud.githubusercontent.com/assets/12820357/19448162/76be32f8-9455-11e6-8f9d-8531b34bb478.png)

![image](https://cloud.githubusercontent.com/assets/12820357/19448216/bd9c3b84-9455-11e6-8ac6-7af2f130733e.png)

**Comment by MikhailArkhipov** [comment]
It is 'loaded via a namespace (and not attached)`

**Comment by MikhailArkhipov** [comment]
http://stackoverflow.com/questions/14988722/in-r-what-does-loaded-via-a-namespace-and-not-attached-mean

_It means the package (In this case R) can access the package functions/objects, **but the user can not** without explicitly loading the tools package_

**Comment by int19h** [comment]
This is not correct - loaded but not attached simply means that it's not on the search path, and therefore its identifiers cannot be used without qualification. But `::` and `:::` should still work, because they work off the list of loaded namespaces, not off the search path. Note how they do work when you actually evaluate R code - you can actually execute `rtvs:::fetch_file`, it's only the code completion that's not working.

If our code completion uses `search()` for this, then we should fix it to use `loadedNamespaces()` instead to be consistent with R.

**Comment by MikhailArkhipov** [comment]
It uses `_host.Session.InstalledPackagesAsync()` so currently only what appears in the package manager

**Comment by int19h** [comment]
Ah, that makes sense. `rtvs` is not a properly installed package, and it won't show up there.

Aside from that issue, this behavior is more correct than `loadedNamespaces` even. Both `::` and `:::` implicitly load the package on the left side before accessing the symbol, so if we want completion to track what R does, then looking at installed (and not just loaded or attached) packages is a right thing to do.

I guess we could just special-case `rtvs` since we always load it. Or make it a proper package - but then we'll have to build it with MinGW and install it via `install.packages` on first load or something...

**Comment by int19h** [comment]
Vaguely related: https://github.com/Microsoft/RTVS/issues/2525

**Comment by MikhailArkhipov** [comment]
I think special casing is fine

**Comment by MikhailArkhipov** [comment]
Unfortunately, we don't provide any RD documentation so there is no signature help.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/5207e29f0beb99a7791dfa56855743ed775801a4
