### ISSUE TITLE
Can't view list when inside a function and subsequent debugger hang

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2535]
```
z <- function(n) {
    x <- as.list(strsplit(Sys.getenv('PATH'), ';'));
    for (e in x) {
        y <- e;
    }
}
```

Set bp on 'for'
Attach debugger
Source
z("foo")

BP hit. In locals, expand `x`
Click on view button on the child entry

![image](https://cloud.githubusercontent.com/assets/12820357/19500014/71a2eff8-954e-11e6-8d7a-901c5754bc4e.png)

Bunch of invalid operation exceptions under debugger
 
![image](https://cloud.githubusercontent.com/assets/12820357/19500024/8150f3e6-954e-11e6-9ec7-a2ed3285ed12.png)

Stop debugging. Note prompt is still `Browse[2]>`
Attach Debugger

'Debugger operation in progress...`

Try canceling. VS hangs.

**Comment by int19h** [comment]
This is specific to the Locals window. Doesn't happen with Variable Explorer, or when using `View()`.

**Comment by int19h** [comment]
The real problem here is that everywhere throughout Variable Explorer code, it ignores `EnvironmentExpression` property of evaluation results, which designates the environment in which the result is valid. To make it work for VE itself, it prepends that expression to the main expression for all results, and trims it for user display. 

A proper fix is to change things everywhere to do it like debugger does, and respect `EnvironmentExpression`. However, that is a fairly big change. So for now, I'll add a workaround on the debugger side here to ensure that the expression passed to the grid viewer has the environment designator as part of the main expression.
