### ISSUE TITLE
Interrupt printing in REPL

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#2550]
Sometimes I'll do something stupid like trying to print a 1-million-row data frame. When this happens, the REPL becomes unresponsive, including the Interrupt R button. All I can do is wait until it's finished (it doesn't crash, mind you, which is good).

Would it be possible to interrupt R while it's in the middle of printing?

**Comment by int19h** [comment]
Do you mean that the Interrupt R button is not clickable, or that when you click it (and there's a visible effect of button clicking), it does nothing?

**Comment by Hong-Revo** [comment]
Interrupt button is not clickable. VS as a whole is still working though, eg I can still edit files etc.

**Comment by int19h** [comment]
Okay, this sounds like UI responsiveness issue on our side. I think we have to hit the message pump every time the REPL prints something out, and it probably saturates it to the point where user input just doesn't make it through.

**Comment by AlexanderSher** [comment]
`_coreShell.DispatchOnUIThread` is not required for Interactive Window to write output, `CurrentWindow.Write` can be called from background thread. But it is required for the text progress bar implementation, which also requires `CurrentWindow.FlushOutput()`. 

We can try to avoid it by separating these cases - use `_coreShell.DispatchOnUIThread` only when `\r` is detected. We just need to be careful  with `_lastMessage` - it should be set to `null` only from UI thread, otherwise it may happen that `OutputBuffer_Changed` will be called after `_lastMessage` is set to null.

**Comment by AlexanderSher** [comment]
Though it won't protect us from 1 million of progress bars :)

**Comment by smortaz** [comment]
I've seen this too
