### ISSUE TITLE
F5 hangs when Remote + Reset R Interactive is on

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2575]
Create new R Project
Right click project, Properties
Check Reset R Interactive on run
Check Transfer files on run
Connect to remote R, wait for REPL to be ready
Press F5 to run

Result: Debug is Starting progress bar dialog that doesn't go away.

If you don't check "Reset R Interactive on run", it works fine.

**Comment by int19h** [comment]
The root cause is that to reset the REPL, we need to do an HTTP request, and that HTTP request requires us to authenticate via CredUI. Eventually it ends up invoking `SecurityService.GetUserCredentialsAsync`, which then tries to switch to the main thread to call the CredUI function on it:

https://github.com/Microsoft/RTVS/blob/43a99131b3b2d1cff6bd6357c8ae3020b921a817/src/Common/Core/Impl/Security/SecurityService.cs#L40

Problem is, the UI thread is blocked at that point by VS debug manager code (which we do not own), and it won't unblock until we finish launching. So we end up deadlocking.

@AlexanderSher, do you recall why we need to switch to main thread there? Since it creates its own UI (with its own message loop), rather than changing existing UI, I'd expect the CredUI stuff to work if it is called from a background thread - was it not the case?
