### ISSUE TITLE
Import dataset is unresponsive for large CSV files

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2583]
For example, do this:

``` r
m <- matrix(1:1000000, 1000, 1000)
```

Then export the variable to CSV, and try to import it. The "Import Dataset" dialog (which is modal) that opens is unresponsive for several dozen seconds, while it's trying to generate the preview of the data. No progress indicator appears, either.

**Comment by MikhailArkhipov** [comment]
```
                using (DataTransferSession dts = new DataTransferSession(session, fileSystem)) {
                    var total = await session.GetBlobSizeAsync(csvDataBlobId, CancellationToken.None);
                    progress.Report(new ProgressDialogData(0, statusBarText: Resources.Status_WritingCSV, waitMessage: Resources.Status_WritingCSV));
                    await dts.FetchAndDecompressFileAsync(new RBlobInfo(csvDataBlobId), fileName, true, new Progress<long>(b => {
                        var step = (int)(b * 100 / total);
                        progress.Report(new ProgressDialogData(step, statusBarText: Resources.Status_WritingCSV, waitMessage: Resources.Status_WritingCSV));
                    }));
                    progress.Report(new ProgressDialogData(100, statusBarText: Resources.Status_WritingCSV, waitMessage: Resources.Status_WritingCSV));
                }

```

can use more stage messages than just 'Resources.Status_WritingCSV'

**Comment by MikhailArkhipov** [comment]
Also, no cancellation tokens passed so cancel on the dialog probably has little effect.

**Comment by karthiknadig** [comment]
It looks like the unresponsive-ness occurs while WPF is trying to construct the data grid after we assign the item source. Without virtualization i don't see a way to make this responsive. I had a brief discussion with @MikhailArkhipov. I recommend closing this bug. @jflam let me know your thoughts.

**Comment by jflam** [comment]
Can we drop in a modal dialog while it's binding the data grid so that folks don't think it's hanging?

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Dec 13, 2016 at 12:19 PM -0800, "Karthik Nadig" <notifications@github.com<mailto:notifications@github.com>> wrote:


It looks like the unresponsive-ness occurs while WPF is trying to construct the data grid after we assign the item source. Without virtualization i don't see a way to make this responsive. I had a brief discussion with @MikhailArkhipov<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMikhailArkhipov&data=02%7C01%7Cjflam%40microsoft.com%7Cb9534bab33d74f59b70708d42395458b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636172571399305773&sdata=Nq1m20GwWX0kdIkXZ31RoaAx2e0E7KMpUAKdoBtIcMY%3D&reserved=0>. I recommend closing this bug. @jflam<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjflam&data=02%7C01%7Cjflam%40microsoft.com%7Cb9534bab33d74f59b70708d42395458b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636172571399305773&sdata=VL1PFJL6pl5nxIxEK0duwFzaDa1JzH78YKwmCnhlc7w%3D&reserved=0> let me know your thoughts.

-

**Comment by MikhailArkhipov** [comment]
This is quite a bit of work for a pretty artificial scenario (million columns - not rows). Control is virtualized for rows, column virtualization is not supported. I'd rather invest time elsewhere.

**Comment by jflam** [comment]
Quite a bit of work to virtualize or quite a bit of work to add a modal dialog box? Not asking for virtualization.

Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by MikhailArkhipov** [comment]
Both. When do we add it? Always - not really, this will unnecessary flicker. How many rows? And it has to be modal BUT allow the UI thread to continue working (i.e. pumping wait).

**Comment by jflam** [comment]
In that case I'm fine with closing it. Agree we have bigger fish to fry.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Dec 13, 2016 at 12:41 PM -0800, "Mikhail Arkhipov" <notifications@github.com<mailto:notifications@github.com>> wrote:


Both. When do we add it? Always - not really, this will unnecessary flicker. How many rows? And it has to be modal BUT allow the UI thread to continue working (i.e. pumping wait).

-

**Comment by int19h** [comment]
Our regular data grid (the stuff used for `View`) is virtualized for both rows and columns. Is this a different control?

**Comment by karthiknadig** [comment]
`View` uses `MatrixView`, this uses `System.Windows.Controls.DataGrid`.
