### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by rnpandya** [Microsoft/RTVS#2628]
Some small but annoying UI issues:
1. I turn off outlining and the R toolbar, and it does not remember that - it comes back very time when I restart VS
2. Ctrl-shift-S in VS usually means Save All Files, but if I'm in an R window it sources that file - very unexpected
3. The R Interactive tab keeps popping to front at random times when I'm debugging a C++ program in the same VS instance

Additional information:

OS Information
    Version:       Microsoft Windows NT 6.3.9600.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.4.20623.1711, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\Microsoft\MRO-3.3.1\

**Comment by MikhailArkhipov** [comment]
(1) is by design in VS. The editor does not keep outlining settings.
(2) - you have a choice to use 'data science settings' that match R Studio or use default VS. You can also re-bind keystrokes to your preference in Tools | Options | Keyboard.
(3) - please update to RTVS 0.5 at https://aka.ms/rtvs-current

**Comment by rnpandya** [comment]
(1) I have outlining turned off globally in Settings, but the R windows do not respect that - all my other windows come up without outlining. And hiding the toolbar is persistent for all the other toolbars, but not for the R toolbar.

Thanks,

Ravi

**Comment by cg31** [comment]
The Toolbar is really annoying when it can't remember the status.

**Comment by MikhailArkhipov** [comment]
There is no global setting for outlining, some languages offer the option:

![image](https://cloud.githubusercontent.com/assets/12820357/20771484/728576f8-b6fe-11e6-95ba-eb49d2b80a88.png)

Basic == Visual Basic rather than global setting. So only VB, C#, C++ and XML offer the setting. All other languages only have it per file (Edit | Outlining | Stop Outlining) and that one is not persistent.

**Comment by MikhailArkhipov** [comment]
Will be adding the option and will fix the toolbar visibility

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/9a664aa23f112177dc3747f5653a650dfcbb6aba
