### ISSUE TITLE
RHost Session is never terminated

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2631]
RHost sessions don't seem to be terminated after RTVS "disconnects" (laptop closed/VM deleted etc). My test server is showing sessions that were created about a week ago still running.

**Comment by AlexanderSher** [comment]
Is it a broker session?

**Comment by karthiknadig** [comment]
Yes, the broker should be killing RHost after the RData is saved. It seems to not behave so in all cases of disconnect.

**Comment by int19h** [comment]
Can you clarify which cases seem to repro this?

FWIW, the broker isn't actually responsible for killing the hosts. It's responsible for letting them know that the client is gone, at which point the host saves the data and kills itself. 

If you have a more or less consistent repro for this on some machine, can you check what `/sessions` returns from the broker when the hosts stick around? i.e. does the broker still consider the session alive, or does it believe it to be gone, and just the host process sticks around?

**Comment by karthiknadig** [comment]
Broker doesn't know about these zombie RHost sessions. Broker believes those sessions are gone, however, the RHost sessions stick around.

**Comment by int19h** [comment]
Yes, this is what Alex has seen in his repro, as well.

But it's not clear to me how this is possible, just looking at the broker code. So far as I can see, the only place where a session is ever removed from the list in `SessionManager` is in response to the event notifying that its state changed to `SessionState.Terminated`. And the only place where that can happen is in response to `Process.Exited` event for the corresponding host process, or when the DELETE endpoint is invoked on a session ID, where this is done after doing `Process.Kill` (and even then this is actually redundant, since `Kill` also triggers `Exited`).

So the only way I can see this to happen is if the process kill was attempted, but failed for any reason. However, this should be reported in the broker log (as "Failed to kill host process for session ...").

Also, why would killing the host process ever fail? The broker clearly does have permissions. I guess it could be some weird Win32 thing with a zombified process; is that something that could be diagnosed by looking at the heap dump of the host?

Either way, I can't seem to be able to repro this. If you have some environment where it does repro with any frequency, can you grab broker & host logs, and host process dump, for investigation?

**Comment by karthiknadig** [comment]
Next time we do a bug bash I will run the `procmon` and keep all the logs from the session. Hopefully that will give a clue into what is going on.

**Comment by int19h** [comment]
Is it fundamentally the same as #2774 ?

**Comment by int19h** [comment]
@karthiknadig, did you see any cases of this repro in the last bash?

**Comment by karthiknadig** [comment]
This did not repro.

**Comment by int19h** [comment]
I think it is safe to conclude that a combination of fixes on the broker and VS side that went in since we saw it fixed this bug. I'm going to close for now, but please keep an eye out for re-occurrences.
