### ISSUE TITLE
Interrupt R is disabled but REPL is busy

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2671]
RTVS_2016-11-08.3

I've issued some plot commands to remote, and it was stuck, so I used Interrupt R.  I did that twice.

Then I tried `1+1` which also hanged, but Interrupt R is disabled.

![image](https://cloud.githubusercontent.com/assets/1696845/20119574/ec70f782-a5bd-11e6-92f2-03c4cfb13305.png)

Dump in \\pytools\r\Bugs\2671

Things work fine again after clicking Reset.

**Comment by huguesv** [comment]
Happened again for me.  Remote operation hangs, interrupt, another operation hangs, interrupt, another operation hangs, and now you can't interrupt because it's disabled.

**Comment by MikhailArkhipov** [comment]
Maybe need to remove

```
        private void OnBeforeRequest(object sender, RBeforeRequestEventArgs e) {
            _enabled = e.Contexts.Count != 1; // Disable command only if prompt is in the top level
        }

        private void OnAfterRequest(object sender, RAfterRequestEventArgs e) {
            _enabled = true;
        }

```

**Comment by int19h** [comment]
The check itself makes sense. If we are hitting it, a better question is why there's more than one active context. Either we're reporting the contexts wrong, or our interrupt (cancellation) is putting R in a really weird state.

**Comment by int19h** [comment]
@huguesv, how easy is it to get into that initial "hang" state? If you have the plotting script that does this often enough, could you share it?

**Comment by huguesv** [comment]
The project I usually start with is in \\pytools\r\Samples\NewPlotExamples
By the end of the bug bash, the hang was becoming easy to repro, but I don't know if it was due to prior actions, current load of the machine, etc.

**Comment by int19h** [comment]
Simplified repro:
```r
xs <- 1:1000000
plot(xs)
```
Repeat the last line, interrupting it every time. Eventually you get to the point where the plotting is happening, but Interrupt command is disabled.

Furthermore, if you just wait for it to complete, it eventually does complete (and display the plot), but REPL doesn't show the new prompt. It is likely that the actual issue here is the latter - i.e. the Interrupt command logic is valid, but the R session itself loses track of the current state.

**Comment by int19h** [comment]
The real problem here is that cancellation can take a long time for a very complicated plot, but the REPL displays the input prompt *as soon as cancellation is requested* (i.e. it doesn't wait for it to actually complete).

So when you type something in the REPL and press Enter, it's actually still waiting for cancellation of the previous evaluation to complete. Because that cancellation is still in progress, the "Interrupt R" command is disabled (you can't interrupt the interrupt). But to the user, it looks like they have already started a new eval, and that eval cannot be interrupted for some reason.

@AlexanderSher, do you recall why REPL behaves that way? Can we do something to make it so that it doesn't show the prompt until cancellation is complete? This is specifically for `RSession.CancelAllAsync`, which does return a task that corresponds to the operation progress (i.e. if you `await` on it, it only completes once cancellation is complete).

**Comment by AlexanderSher** [comment]
The original problem to cancel all pending evaluations and interactions before we actually cancel it on the host side is to prevent them from being pulled from the queue. But I think it is safe to call `currentRequest?.TryCancel(exception);` after `await cancelTask`

**Comment by int19h** [comment]
I don't think that's the issue. I see the cancellation request arriving to the host in the logs as soon as I click "Interrupt", so cancelling evals wasn't unduly delaying it. The problem is that the host sometimes cannot cancel immediately - cancellation fundamentally requires R to be cooperative and invoke the host callback every now and then, and it doesn't always do so.

In this case, there's a significant (seconds) delay between host receiving the cancellation request, and host reporting that cancellation was complete, and then that there's a new prompt. But the REPL shows an input prompt as soon as cancellation request is _sent_ to the host, not when notification that it's complete is received.

**Comment by AlexanderSher** [comment]
Maybe I don't understand you, but when you call `currentRequest?.TryCancel(exception);`, it releases `RSessionRequestSource._responseTcs.Task`, which is awaited in `RInteractiveEvaluator`
And cancelling pending evals was put before `await cancelTask` not because they were delaying something, but because R began processing the queue before interactive window could return control to the user.

**Comment by int19h** [comment]
Ah, I see now. But isn't the problem here rather that `RInteractiveEvaluator` is awaiting on the wrong thing? It would seem that we *do* want any current request task to report being cancelled as soon as cancellation is issued (even if the host might take some time to actually cancel execution). But why does REPL wait on this, rather than waiting for the next prompt (i.e. `await BeginInteractionAsync()`) to come? It seems to be implemented that way deliberately, and I think we discussed it before, but I don't remember why it is the way it is.

**Comment by AlexanderSher** [comment]
Waiting on `await BeginInteractionAsync()` will immediately give the prompt to the REPL, which will prevent other code from using it. And we actually don't want to release a response task when cancellation is requested - we should release when cancellation is already happened, which matches the way we normally release it when next `?>` arrives, not just when we know that R has received our request.

**Comment by int19h** [comment]
This works, but it kinda moved the problem one step away. Now the REPL doesn't show the prompt immediately once Interrupt R is clicked - but the command itself remains active, and can be clicked the second time! If you do that, the original bug basically repros (i.e. REPL shows a "fake" prompt despite cancellation is still ongoing).

Looking at the logs, only one cancellation request is actually sent to the host, so the second click is a no-op, other than giving confusing REPL state.

Any objections to just disabling the command while it's being executed? Are there any other issues that could surface due to this from other code paths?

**Comment by AlexanderSher** [comment]
Is it our command (`InterruptRCommand`)?

**Comment by int19h** [comment]
Yep.

**Comment by AlexanderSher** [comment]
Then we probably need to change `AsyncCommandController` so that instead of `DoNotWait` it calls `ITaskService.Wait`

**Comment by AlexanderSher** [comment]
Or maybe provide this type of behavior as an option.

**Comment by int19h** [comment]
Disabling this particular command is much easier than that - it already has that logic, it just does it at the wrong time. I'll just move that around (literally swapping a couple of lines).
