### ISSUE TITLE
Optimize logging

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2679]
- Remove `async/await`
- Replace StringBuilder with Queue
- Trigger flush by timer or by threshold
- Customize log path for tests
- Put logs into subfolder inside TEMP

**Comment by Hong-Revo** [comment]
Will this affect the size of the log files generated? I noticed that some of the RTVS logs were ~1GB in size.

**Comment by MikhailArkhipov** [comment]
Logs are generally trimmed to 1MB. Are you seeing large files or just a lot of logs? Retention policy is 5 days. In the next update there is a setting for the log level in options so it is now possible to reduce or switch off logging.

**Comment by MikhailArkhipov** [comment]
Moving to Sprint 9

**Comment by int19h** [comment]
Logs are so huge because they currently capture all traffic between VS and R, so something goes there every time some R expression needs to be evaluated for any reason. It's basically the equivalent of "debug" logging verbosity, to help us diagnose issues faster. As Mikhail said above, we're reducing that verbosity level by default in the future release.

**Comment by MikhailArkhipov** [comment]
Close? Most of the things are done I believe.

**Comment by AlexanderSher** [comment]
Yes, the remaining is actually part of the #2734 .
