### ISSUE TITLE
Connecting to remote needs user feedback msgs

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#2683]
1. Located <hostname> successfully... done.
2. Initializing Remote R process... done.
3. Closing previous R session... done.

**Comment by AlexanderSher** [comment]
@jflam , @MikhailArkhipov  
Do you have any input on this task? I want to estimate it

**Comment by jflam** [comment]
The idea behind this task is to remove some of the uncertainty behind what the service is doing while you are waiting for the connection. It would also be helpful to use this as a way to report errors as well. It would be helpful if you could provide a list of the distinct "events" that comprise the time taken to connect to the service. Here's some examples without knowing the specifics:

1. Looking up the name of the remote server
2. Establishing HTTPS connection to the remote server
3. Creating user profile on the remote server
4. Creating R session on the remote server
5. Connected

For example, if it fails on #1, we could say " -- could resolve the name of the remote server". If it fails on #2, we could say " -- could not establish connection to the remote server".

So I would say, let's come up with a concrete list of the event names. Next, we should figure out what we do in the event of an error: Here's a strawman: the connection dialog halts, display an error message next to the name, along with an OK button to acknowledge the error. When the user clicks OK, we dump a detailed log of what was done and what the last known state was to the console window to make it easier for the user to copy / paste into a report about the error - keep in mind that those reports may be sent to their local admin vs. us, the RTVS team.

**Comment by smortaz** [comment]
what john said.  +1.

**Comment by AlexanderSher** [comment]
Right now, we have 2 separate steps:
- Start RHost for the new broker
- Restart RSession 

We can split them further, but I'm not sure that will give any valuable information to the user.

**Comment by MikhailArkhipov** [comment]
Correct, we don't really have all those stages. We don't look for machine first, it is part of Http request and is internal to the stack. There is no feedback from the server on stages it is coming through.

Also, 

https://github.com/Microsoft/RTVS/pull/2766
https://github.com/Microsoft/RTVS/issues/2749

make connection switching much faster

**Comment by jflam** [comment]
I'm mostly looking at this through the lens of providing useful information for the user. So I don't mean *literally* translating what we do internally into a sequence of steps, but rather providing the user with a logical set of things that we do that can fail, and showing that to the user. i.e., we can say "looking up server" as part of the initial HTTP connection so that we can fail with message 1 below. Assuming that the connection succeeded but the server doesn't have a cert installed, we can fail with message 2 below. etc.

1.  So, is there a distinguished exception that is returned from the HTTP stack if the user mis-typed the DNS/NETBOIS name of the server? If so, we should have a clear message that tells them that.

1. If the server is misconfigured somehow such that HTTPS is not enabled, what error message do we provide the user?

1. If the user profile fails to be created on the server (thereby rendering the entire environment more or less useless), what error message do we report to the user, and how is this actionable for them or their server admin?

**Comment by MikhailArkhipov** [comment]
1 - yes, it should output exception message similar to 404
2 - yes, most probably returns 'server is online but Remote R service is not running. I don't think we can tell from the client side that certificate is misconfigured as broker won't even start if there is no certificate (logged at the server side).
3. @karthiknadig - is there any diagnostics or does user just get 401 Unauthorized?

**Comment by karthiknadig** [comment]
3 is currently reported as an authentication failure to the User. The ETL events, for the R user profile service, contains details of what happened.

**Comment by MikhailArkhipov** [comment]
User probably has little knowledge or means what has to be done on the server. However, admin can look at logs and system events per complaint from the user.

**Comment by MikhailArkhipov** [comment]
So, bottom line

```
Looking up the name of the remote server
Establishing HTTPS connection to the remote server
```
Are part of the same call. We do not manually look up DNS.

```
Creating user profile on the remote server
```
We don't know if it is being created. Broker has no means to report this.

So basically there are only two steps:

1. Establish connection
2. Create session.

**Comment by MikhailArkhipov** [comment]
We've added more information to errors, shiny messages etc. We don't have more information at the moment.
