### ISSUE TITLE
AF in cat(), argument type mismatch in protocol message

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2721]
Reported as crash in 0.5, need to check what is going on there

```
x <- "2016-11-19T20:21:41.7452661"
cat(x)
```

in

```
            if (arg.Type != expectedType1 && arg.Type != expectedType2) {
                throw ProtocolError($"{name} must be {expectedType1} or {expectedType2}:", this);
```

arg.Type is `Date` while code expects `String`

**Comment by MikhailArkhipov** [comment]
If instead of throwing we just return the token (since pretty much anything can be a string), everything works OK.

**Comment by int19h** [comment]
On it.

**Comment by int19h** [comment]
Okay, so this is an absolutely insane design decision by Json.NET:

https://github.com/JamesNK/Newtonsoft.Json/issues/862

Basically, if a string literal looks like an ISO date, they deserialize it as `DateTime` by default!

Removing the check won't fix it, because then trying to get the string value of the JSON token will actually do `DateTime.ToString` under the hood, with current locale. So you'll see the .NET interpretation of what a date represented by that string should look like, instead of the original string (which isn't even a date in R).

The fix is to explicitly specify `DateParseHandling.None` anywhere JSON is deserialized - any call to `JsonSerializer.Deserialize`, `JsonConvert.Deserialize*`, or `J*.Parse` is affected.

Worse yet, this is affected by `JsonConvert.DefaultSettings`, which is global (static). So depending on what it's set to, this may or may not repro. Of course, everything that uses Json.NET inside Visual Studio shares this global, so we can't just change it - it will affect others.

I couldn't repro it on Dev15, and I suspect it is because it changes  `JsonConvert.DefaultSettings` to something sane.

**Comment by MikhailArkhipov** [comment]
Perhaps make a wrapper and then replace all abovementioned calls by call to the wrapper?

**Comment by int19h** [comment]
Yes. I'll just need to make sure that I get all of them wherever they might be in our code...

**Comment by MikhailArkhipov** [comment]
Closing in favor of #2729
