### ISSUE TITLE
Connection should not turn green until REPL opens

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2736]
Without REPL opened, open Wokspaces and try connecting to remote. Progress is displayed, then progress dialog closes, connection turns green but REPL doesn't open. After several seconds (~10) REPL finally opens.

the operation should be considered complete when everything is in place and ready.

![image](https://cloud.githubusercontent.com/assets/12820357/20542247/ad05861e-b0b5-11e6-9c09-908d98f5f5f1.png)

**Comment by AlexanderSher** [comment]
We have no way to control when REPL will appear. What happens is that we send command to show REPL and it tries to create its `RSession` from UI. Since we lock `RSessionProvider`, it can't create its session until switch is completed and so can't appear. If we show REPL before we start switching, user will see error message from NullBroker.

Proper solution is to add 4th status - connected but no REPL session. Can we request icons for the statuses?

**Comment by MikhailArkhipov** [comment]
More statuses confuses users. Perhaps null broker should never be showing messages. Then it would be safe to open repl first.

**Comment by AlexanderSher** [comment]
It doesn't show anything by itself. Interactive Window tries to connect to it and shows an error, which is a correct behavior if you're not connected to any other session. Interactive Window has no idea that we're going to try to connect right after it creates the session.

**Comment by AlexanderSher** [comment]
Ok, the main delay happens on the UI thread. Interactive Window shows up several seconds after RHost receives `?>` message, which itself happens after `RInteractiveEvaluator.InitializeAsync` is completed.
So if we want to show green only when interactive window is initialized, we need to track this specific moment.
There is a `LastActiveWindowChanged` event in `IActiveRInteractiveWindowTracker`, but no one uses it. So I remove it from there and add `ActiveWindowChanged` to the `RInteractiveWorkflow` itself.

**Comment by AlexanderSher** [comment]
Btw, `RInteractiveWorkflow` provides access to `ActiveWindow` before it is initalized. I was sure that I've fixed it for the 0.4 release.
