### ISSUE TITLE
View() fails for list with externalptr

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2756]
From customer logs

```
[16-11-23_10-50-39]:Grid data evaluation failed:
                    R evaluation failed:
                    rtvs:::grid_data(as.environment(".GlobalEnv")$result, 1:10, 1:1, )
                    Error in prettyNum(.Internal(format(x, trim, digits, nsmall, width, 3L,  : 
                      first argument must be atomic
                    
```

Minimal standalone repro:
```r
library(httr)
langResult <- POST("https://westus.api.cognitive.microsoft.com/text/analytics/v2.0/languages?numberOfLanguagesToDetect=1")
View(langResult)
```

**Comment by int19h** [comment]
Can you add the part of the logs that initialized `result`?

**Comment by MikhailArkhipov** [comment]
Might be something private, I'll e-mail you

**Comment by int19h** [comment]
The fundamental problem is that this data structure includes a value of fundamental type "externalptr" (in this case, for `curl_handle` C typedef in the native library it wraps), which `format` cannot handle.

**Comment by int19h** [comment]
Unfortunately, there doesn't seem to be any good way to handle this. The problem is that any particular element can be of a weird type (in this case, it's 1 element out of 10 in a column, and there are several columns). We currently use `format` in a vectorized manner, column-by-column, and so if any single element fails, the whole column fails. To do a proper fallback, we'd need to format element-by-element, but that would slow the grid down significantly, and affect the much more common cases where there's no weird elements.

Detecting this condition in advance also requires enumerating all elements, and comes with a similar perf cost.

So it seems that we have to deal with the fact that some collections are just not `View`'able, and that we cannot always reliably predict this in advance - in other words, we'll show the magnifying glass icon, but when you click on it, it can still fail. 

The other problem here is that if underlying evaluation fails, all you see is a weird error message printed out to the console, and the grid viewer puts the entire R session in a bad state (REPL doesn't work etc). So the fix here is to improve error reporting, and ensure that nothing else breaks.

**Comment by MikhailArkhipov** [comment]
What happens in RS?

**Comment by int19h** [comment]
RS fails outright, because it only supports `View` for something that can be converted to a data frame (and because it always performs that conversion, it sometimes loses data or converts it in weird ways for sources that aren't originally data frames).

We support a much broader set of types, but have to deal with corner cases like these.

**Comment by int19h** [comment]
To be specific, in RS, you get this printed out to the REPL, and no grid:
> Error in View : cannot coerce class ""response"" to a data.frame

**Comment by MikhailArkhipov** [comment]
So at least RTVS is not worse :-)

**Comment by int19h** [comment]
Well, not right now :) since in RS, you can continue to use the REPL afterwards. In RTVS, it currently gets stuck, because VE messes things up when eval fails.

**Comment by MikhailArkhipov** [comment]
So it looks like by design at the moment and not immediately fixable.

**Comment by int19h** [comment]
So my initial assessment was wrong. We do, in fact, already iterate over single elements anyway (for other reasons), and so `format` can be de-vectorized without a substantial perf hit, and then any errors coming out of it can be handled on a case-by-case basis. A fix along these lines is coming shortly.

I've spent significant time trying to figure out why eval failure puts the R session into an unusable state, but it's way more complicated than I originally expected (and looks like it has nothing to do with VE itself). This should probably be pursued separately, but with a fix to the grid code, it is no longer a user-observable scenario, so its priority changes accordingly.
