### ISSUE TITLE
Consider adding support for lintr

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2767]
lintr provides static code analysis for R - https://github.com/jimhester/lintr

There is already integration for a number of different editors and IDEs, including vim, emacs, Sublime, Atom, and RStudio.

![image](https://cloud.githubusercontent.com/assets/8877/20698248/905b551c-b5b4-11e6-8cb7-2e327ccd0c90.png)

**Comment by MikhailArkhipov** [comment]
It may be relatively simple to add this diagnostics to our AST. We already have async processing as you type (rather than running package command in R in sync on the entire file) and full integration with error list etc. It is simple to output these as warnings or information. Multi-file handling is doable as well.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/f654cfd573f15c2fbf477393bfb6675359d9422e
