### ISSUE TITLE
Disable delete in Variable Explorer for sub items?

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2813]
Create a variable
```
dd <- matrix(nrow = 5, ncol = 1)
```

In Variable Explorer, expand `dd` and right-click on one of its subitems.  Select Delete.
```
> rm([[4]], envir = as.environment(".GlobalEnv"))
Error: unexpected '[[' in "rm([["
> 
```

Should Delete just be enabled for top level items?

**Comment by int19h** [comment]
It should be enabled for environments, including nested environments. But it's currently broken for nested environments also - that's just a bug in the code, because it should specify the right environment in the call to `rm`.

It should be disabled for anything that is not an environment.

As a quick mitigation, yes, we probably just want to disable it for non-top-level items until the proper fix.

**Comment by int19h** [comment]
For nested environments, I mean:
```r
e <- new.env()
e$x <- 123
```
You should be able to delete `x`, and what it should do is `rm('x', envir = as.environment(".GlobalEnv")$e)`.

**Comment by MikhailArkhipov** [comment]
No complaints. Cleaning up backlog
