### ISSUE TITLE
Host crashes after interrupting, then running another command

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2881]
```

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Microsoft R Open 3.3.2
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2016 Microsoft Corporation

Using the Intel MKL for parallel mathematical computing(using 6 cores).

Default CRAN mirror snapshot taken on 2016-11-01.
See: https://mran.microsoft.com/.


R Services Information:
	Remote workspace 'rtvs-devserver1' : https://rtvs-devserver1:5444/
	Version: 0.6.21212.2248
	Operating System: Microsoft Windows NT 6.2.9200.0
	CPU Count: 12
	Physical Memory: 65459 MB, 60587 MB free
	Virtual Memory: 75187 MB, 69836 MB free
	Video controller: NVIDIA Quadro K600
	GPU: Quadro K600
	Video memory: 1024 MB
	Connected users: 3

⚹> ?data
starting httpd help server ...
 done

⚹> ?data


R Host process is stopped. Click "Reset" to start a new one.


Interactive Window is disconnected from R Session.
Click "Reset" to start a new session.
⚹> 
```

Logs at pytools\r\bugs\2881.

**Comment by int19h** [comment]
This is a combination of #2818 and by-design behavior in the host (#2671 is also relevant).

So far as I can see, what happened here is that after interrupting the first `?data`, the cancellation completed successfully, host sent notification to VS that everything was canceled, and also sent a new request for input (corresponding to the new prompt). However, VS itself is still awaiting the help callback in the message processing loop in `RHost`, and so it didn't see the new prompt coming in.

The REPL, meanwhile, lets you type and queue expressions for execution even if R is busy, so it shows a new "fake" prompt. When you type something at that prompt, the REPL initiates an interaction to respond to the real prompt - but because the message loop hasn't seen the new prompt yet, nor the cancellation response invalidating the _old_ prompt, it responds to that old prompt - i.e. the message that gets sent to the host is a response message specifying as request ID a prompt that was already cancelled. The host treats it as a fatal error and kills itself.

The problem here is that there's a race condition between cancellation (interrupt) and answering the prompt. To fix this, either `RSession` needs to block the queue during cancellation until it completes, or else `RHost` needs to ignore any return value from `ReadConsole` callback if the cancellation token is signaled by the time the callback returns (even if the callback returns successfully, producing a value) - i.e. do not send a response message with the returned value. It feels like the latter approach is the more generic one, and I think it needs to be done for all callbacks consistently, not just `ReadConsole` (since all outstanding blocking callbacks are interrupted by cancellation).

@AlexanderSher, what do you think?

**Comment by int19h** [comment]
It's not possible to reproduce the original bug anymore due to all the other fixes. However, me and @AlexanderSher have spent some time analyzing the code path, and concluded that potential for a race condition leading to the same crash still exists, albeit it's much harder to trigger now. Consequently, a targeted fix is coming shortly.

**Comment by zepen** [comment]
i have not find R install. why? just this information "Interactive Window is disconnected from R Session." when i open a R project in the vs

**Comment by MikhailArkhipov** [comment]
Try R Tools | Windows | Workspaces and select R you want to use.
