### ISSUE TITLE
Integrate with Windows credentials dialog

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2966]
I.e.

![image](https://cloud.githubusercontent.com/assets/12820357/21701563/1e570e60-d35b-11e6-9559-5c0058b8ba88.png)

So users can choose different credentials or get proper 2-factor or smartcard auth

**Comment by int19h** [comment]
As I recall, we will get this if we start using `CredUIPromptForWindowsCredentials` instead of `CredUIPromptForCredentials`.

The problem is that it doesn't automatically give us support for other fancy types of auth. That function is more generic, and it doesn't just return you a username/password pair - it returns a generic blob that contains credential payload that is specific to the provider that user chose. Since right now we use HTTP basic to pass credentials, we can only handle username/password, so those other types won't work until we plumb through the whole thing to the server (and possibly to user profile service). 

There's also the question of what happens if the server isn't Windows. In this case username/password is really the best we can do. And the old-style dialog doesn't really care if that username isn't a Windows username. I'm not sure whether it'll still be true for the new one.

So this is potentially a very huge item, with plenty of investigations, and likely a lot of code. I doubt it'd fit in RTM, unless we explicitly support username/password input only and nothing else; but then the new dialog doesn't actually offer any advantages, except for styling, and in fact will be deceptive in that some options offered won't even work.

**Comment by int19h** [comment]
It looks like we can use the new dialog but tell it that we *need* credentials in clear text via `CREDUIWIN_GENERIC`. In this case I expect it to omit any providers that cannot service that request from the list. Then we can assume that `CredUnPackAuthenticationBuffer` can be used to extract data from the blob. 

Remains to be seen which providers (PIN, smartcard etc) will actually remain available with this flag though.

**Comment by MikhailArkhipov** [comment]
[CredUnPackAuthenticationBuffer](https://msdn.microsoft.com/en-us/library/windows/desktop/aa375185(v=vs.85).aspx)  ?

**Comment by MikhailArkhipov** [comment]
Oh, saw you comment after

**Comment by karthiknadig** [comment]
For the User Profile service, there is a way we can eliminate the need to send username/password entirely. I'l do that as a part of the Broker as a service change. I agree with @int19h, I try a prototype and see which providers  are supported with generic.
