### ISSUE TITLE
R Interactive print slow

### ISSUE THREAD

**Issue by Victsz** [Microsoft/RTVS#3000]
The print function is very slow, while system.time function result is reasonable.

The following snippet takes around **10 secs** in reality to display on R Interactive window.
x<-c(1:5000) 
system.time(print(x))
0.92 0.15 0.80 

You may check https://youtu.be/LO3mgTnxC5k
I also encountered #2561 #2996 not sure if they are relevant.

...

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

![image](https://cloud.githubusercontent.com/assets/8154646/21917186/f87bd280-d980-11e6-9fa8-1d14ccbaaf9c.png)

Additional information:

OS Information
    Version:       Microsoft Windows NT 6.3.9600.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.5.21201.1213, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\Microsoft\R Client\R_SERVER\

**Comment by smortaz** [comment]
here's my run from lenovo carbon laptop:

[image: Inline image 1]

**Comment by Victsz** [comment]
Sorry, can`t see your image.
But the system.time did not reflect the actual time from print till I really saw the output.

**Comment by MikhailArkhipov** [comment]
![image](https://cloud.githubusercontent.com/assets/12820357/21939296/fcce7d40-d973-11e6-8bb0-49b4a4239c35.png)

**Comment by MikhailArkhipov** [comment]
```
        Span IInteractiveWindow.Write(string text)
        {
            return UIThread(uiOnly => uiOnly.Write(text));
        }
```

**Comment by MikhailArkhipov** [comment]
We could try and batch on bg thread and write in bulk every 100-200 ms instead

**Comment by Victsz** [comment]
I am not sure where the problem is but it does happened on my machine which it`s clean install environment. 
You may check my youtube link https://youtu.be/LO3mgTnxC5k
I also tried on R studio and it was fine.

**Comment by Victsz** [comment]
Could you tell me how to get to hot path widow as yours? I dont know how to attach a performance profiler to R project

**Comment by MikhailArkhipov** [comment]
There is no R profiling in VS yet. However, R has its own means

http://adv-r.had.co.nz/Profiling.html
https://www.r-bloggers.com/profiling-r-code/
https://rstudio.github.io/profvis/

**Comment by int19h** [comment]
I have implemented a buffering solution, but it doesn't solve the perf problem - the gain is less than 5% either Dev14 or Dev15, even when flush timeout as slow as 500ms, and we're still an order of magnitude slower than RStudio.

Looking at the profiler, it appears that most of CPU time is spent in `WebSocketMessageTransport`, receiving messages - it's 70% of all CPU time. Another 10% is spent parsing them.

For receiving, most time is spent inside `CommonWebSocket.ReceiveAsync` (which is not our code, so there's no further drill-down).

The next most expensive item is allocation of the receive buffer - we do it on every receive, but we should really just reuse the same buffer. Doing that gives another 10% boost. 

Still, the biggest problem by far is the sheer number of messages being sent. It seems that to really do any meaningful improvements here, we need to batch output messages on the host side, so that rapid printing like this only produces a few websocket packets. This is doable, but certainly a bigger change than client-side buffering - worth pursuing?

**Comment by int19h** [comment]
Some more food for thought. The problem with `print` is that it prints (as in, calls `WriteConsole`) *every element* separately, not even every line. In other words, when you do `print(1:10)`, you get ten messages - plus extras for bracketed line numbers and newlines. Log:
```
==> #138# :> #17# [  "print(1:10)\n" ]
<== #155# !+ []
<== #157# ! [" [1]"]
<== #159# ! ["  1"]
<== #161# ! ["  2"]
<== #163# ! ["  3"]
<== #165# ! ["  4"]
<== #167# ! ["  5"]
<== #169# ! ["  6"]
<== #171# ! ["  7"]
<== #173# ! ["  8"]
<== #175# ! ["  9"]
<== #177# ! [" 10"]
<== #179# ! ["\n"]
<== #181# !- []
<== #183# ?> [[0],4096,true,null,"> "]
```
This is why it puts so much strain on the transport layer - the overhead here is insane, we're talking about thousands of tiny 10-byte messages (each of which then gets wrapped into a WS packet, which is wrapped into a TCP packet, which is wrapped into an IP packet etc). 

This can also be observed in a more controllable way, by playing with `cat` like so:
```r
xs <- 1:20000
s <- paste0(xs, collapse = '\n')

system.time(cat(xs, sep = '\n'))
system.time(cat(s))
```

The two timed calls print out the same exact output, except that the first one does it by printing every element separately, while the second one concats them all into one string and prints that in a single `WriteConsole` call. The difference is two orders of magnitude.

**Comment by MikhailArkhipov** [comment]
Yes, I observed the same when tracking output. `1+1` produces separate `[1]` followed by `2`. Could we buffer until line break or, say, 100ms passed?

**Comment by int19h** [comment]
Buffer where? Doing it in VS doesn't help - see analysis above.

Doing it in the host would help a lot. But it's complicated, because currently the host is effectively single-threaded: it has a second thread to receive and queue requests, but it processes requests and sends messages only from the main thread on which R runs. To have a buffering window with a timeout, it would require a second thread to keep track of that buffer and timeout and flush accumulated data (since we cannot rely on R callbacks to do this - there's no guarantee of them happening periodically, R can be stuck on something indefinitely). And that thread also needs to synchronize with the main thread, since all callbacks must still be reported in the same order in which R gives them to us, so anything other than a write must cause a flush.  This is a rather drastic change, and esp. the synchronization part makes me nervous churn- and stability-wise.

**Comment by huguesv** [comment]
Buffering on the host side sounds a lot like what is done for plotting (and probably even worse). I'd be nervous making that change too ;)

**Comment by MikhailArkhipov** [comment]
Yes, in the host in order to reduce traffic. With single thread we'd need something to track idle. No readily available in headless/console apps.  Is there a main thread timer (like dispatcher timer in WPF?) Would something like http://stackoverflow.com/questions/4267546/c-boost-asio-simple-periodic-timer work?

**Comment by MikhailArkhipov** [comment]
If it is complicated, let's postpone then. We can try and use something like https://github.com/stephan-hof/boost_queue/blob/master/concurrent_queue.hpp next time around.

**Comment by int19h** [comment]
The main thread runs a message loop, so we could use Win32 timers. But the problem is that, because R isn't a full-time GUI app, it doesn't guarantee that the message loop is pumping. Any blocking call (e.g. `readline`) prevents it from doing so for a potentially indefinite amount of time. Hence the need for a separate thread to run the timer on. 

Long-term solution would indeed be to *queue* the messages from main thread, and actually send them from the background thread with a timer. Then that background thread can combine adjacent messages where it makes sense.

However, this would require some kind of intermediate representation for messages that makes it possible to combine them without re-parsing them - right now we construct the message blob immediately before sending, and to combine such blobs, they'd need to be parsed to determine message type and retrieve the actual data to combine. So all places that send messages would need to switch to constructing that intermediate representation instead, and the bg thread would combine those and make blobs out of them. All pretty straightforward, but quite a bit of new code.

**Comment by int19h** [comment]
In the meantime, the workaround is to use `View(...)` for large collections. That one is actually designed to lazily load data, so it will only load the part that is visible on the screen as you scroll around. It can handle even extremely large collections (like, say, a 10000x10000 matrix) just fine in this manner.

**Comment by MikhailArkhipov** [comment]
Postponing

**Comment by MikhailArkhipov** [comment]
Need to re-measure in 1.2 since output window writer was changed to async publisher/consumer queue

**Comment by MikhailArkhipov** [comment]
Old (max.print = 99999)
0.92 0.15 0.80

VS 15.4 (R 3.4.0, max.print = 99999)
0.06    0.13    0.33
0.13    0.08    0.32
0.08    0.07    0.31 

VS 15.4 (R 3.4.0, max.print = 1000 as RS default)
0.03    0.01    0.06
0.04    0.00    0.07 
0.00    0.02    0.06

RS (max.print = 1000)
0.02    0.00    0.01

RS (max.print = 99999(
0.03    0.00    0.03

**Comment by MikhailArkhipov** [comment]
via #3715 and https://github.com/Microsoft/RTVS/commit/bb097aa92ed78b001d738ab73fac190c976d0d51
