### ISSUE TITLE
Remote connection cannot fetch any data from internet

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#3040]
I installed my own server in Windows Server 2012 R2 on xlab, following our instructions on SharePoint.

I'm able to connect to the machine and execute code.

However, any function calls that try to fetch data from the internet, such as:
```
available.packages()
```

or 
```
data <- read.csv('http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')
```

fail with an error:

```
Error in file(file, "rt") : cannot open the connection
In addition: 
Warning message:
In file(file, "rt") :

 
 InternetOpenUrl failed: 'The server name or address could not be resolved'
⚹> 
```

Note: If I do a remote desktop connection, open RGUI and run the same code directly on the server, it works fine.

**Comment by MikhailArkhipov** [comment]
This is actually may be a security feature :-). I believe that HTTP stack is hardened by default. We may have to add step to enable IE regular configuration IF admin permits fetching data from the Web.

**Comment by MikhailArkhipov** [comment]
What happens if you enable regular IE?

**Comment by huguesv** [comment]
You mean this right?
![image](https://cloud.githubusercontent.com/assets/1696845/22169708/16c9433a-df2b-11e6-83b0-4dd0e634e4b1.png)

I only had it off for Administrators, so I turned it off for Users, rebooted the machine, and I'm getting the same error when used from client RTVS.

**Comment by MikhailArkhipov** [comment]
Yes. On my VM which is Windows 10 client, PM and 

```
data <- read.csv('http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')
```

are broken too

**Comment by MikhailArkhipov** [comment]
Test machines set up by magic hand of @karthiknadig everything works fine ;-)

**Comment by karthiknadig** [comment]
Looks like WSH firewall rule blocks any outbound calls from a service. An exception has to be specifically added. https://msdn.microsoft.com/en-us/library/bb736280(VS.85).aspx

**Comment by MikhailArkhipov** [comment]
For now lets just need to document the script that adds the exception.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS-docs/issues/55

**Comment by Ameb** [comment]
Hello! I'm having the same issue when trying to connect to the internet in a remote connection (installing packages, fetching data...) with RTVS.

I have double-checked firewall rules, so i think the problem is related to WSH firewall since we are using Windows Server. 

Is there anything else i can try?

```
OS Information
    Version:       Microsoft Windows NT 10.0.15063.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30817.1931, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    procesaBA: https://procesaba:5444
```
```
⚹> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.850     LC_MONETARY=Spanish_Spain.1252
[4] LC_NUMERIC=C                   LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtilsMath_10.0.0 RevoUtils_10.0.5     RevoMods_11.0.0      MicrosoftML_1.5.0    mrsdeploy_1.1.2     
[6] RevoScaleR_9.2.1     lattice_0.20-35      rpart_4.1-11        

loaded via a namespace (and not attached):
 [1] codetools_0.2-15       CompatibilityAPI_1.1.0 foreach_1.4.4          grid_3.4.1            
 [5] R6_2.2.0               jsonlite_1.4           curl_2.6               iterators_1.0.8       
 [9] tools_3.4.1            compiler_3.4.1         rtvs_1.0.0.0           mrupdate_1.0.1        
⚹> data <- read.csv('http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')
Error in file(file, "rt") : cannot open the connection
In addition: 
Warning message:
In file(file, "rt") :

 
 InternetOpenUrl failed: 'The server name or address could not be resolved'
```

Using `mrsdeploy` it just works, but i´d love to have the awesome RTVS features :)
```
REMOTE> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252   
[3] LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
[5] LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtilsMath_10.0.0 RevoUtils_10.0.5     RevoMods_11.0.0     
[4] MicrosoftML_1.5.0    mrsdeploy_1.1.2      RevoScaleR_9.2.1    
[7] lattice_0.20-35      rpart_4.1-11        

loaded via a namespace (and not attached):
 [1] codetools_0.2-15       CompatibilityAPI_1.1.0 foreach_1.4.4         
 [4] grid_3.4.1             R6_2.2.0               jsonlite_1.4          
 [7] curl_2.6               iterators_1.0.8        tools_3.4.1           
[10] compiler_3.4.1         mrupdate_1.0.1        
REMOTE> data <- read.csv('http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')
REMOTE> head(data)
  X5.1 X3.5 X1.4 X0.2 Iris.setosa
1  4.9  3.0  1.4  0.2 Iris-setosa
2  4.7  3.2  1.3  0.2 Iris-setosa
3  4.6  3.1  1.5  0.2 Iris-setosa
4  5.0  3.6  1.4  0.2 Iris-setosa
5  5.4  3.9  1.7  0.4 Iris-setosa
6  4.6  3.4  1.4  0.3 Iris-setosa
```

**Comment by MikhailArkhipov** [comment]
Can RGUI access internet from this machine?

**Comment by karthiknadig** [comment]
Workaround if RDP is needed: First RDP into the server. Start the broker using the command line below. Be sure to provide a different port number than the default 5444. Now you can connect to this R service while having an active RDP connection. 
```
> "%PROGRAMFILES%\R Remote Service for Visual Studio\1.1\Microsoft.R.Host.Broker.exe" --urls https://0.0.0.0:6000
```
Connect to this broker, by adding a separate connection, as `https://**myremote**:6000`.

More details about the cause:
The issue occurs due to the fact that we create a desktop to host the user session. This is a part of creating the remote R-host session for a user that can load UI components (for interactive R). This desktop session is invisible, and without this desktop no UI dependent DLLs, such as `User32.dll`, that have a dependency on the desktop handle are loaded. When the user logs in using RDP, they get their own desktop session (visible and interactive). This will result in the desktop used by R-Host to be blocked, and hence some OS resources are also blocked. The active RDP session always takes priority here. When the user logs out, the R-host desktop resumes its state. This article goes in depth on the desktop object in mode detail here: https://blogs.technet.microsoft.com/askperf/2007/07/24/sessions-desktops-and-windows-stations/

Enabling WSL on the service will not help here since the R-Host it self is running in user session. WSL applies to service session processes, which in this case is the broker.

**Comment by Ameb** [comment]
The workaround works, starting the broker with elevated privileges. (Via admin cmd or with a shortcut)

Thank you for the explanation, @karthiknadig
