### ISSUE TITLE
Exporting jagged lists to Excel crashes VS

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#3044]
repro <- list(c(1,2), c(1,2,3))

1. Open Variable Explorer. 
2. Click on Excel icon

Crash.

The table viewer works correctly.

**Comment by int19h** [comment]
It doesn't work because you can't create a dataframe out of it, and we need to do so to call `write.table`.

Ideally, we shouldn't actually be showing the icon at all in this case. But it can be very expensive to determine it in the most general case - e.g. we can be looking at a list of 10k elements, of which all are 10-element vectors, except last. The only way to determine that it's not exportable is to scan the whole thing. So currently we just check if `as.data.frame` method is applicable to a given type; we don't actually try to execute it and see if it fails. This means that some false positives, like this one, are going to happen.

So the bug here is that error inside `rtvs:::export_to_csv` is not correctly handled, either by that function itself (easiest), nor by C# code calling it.

**Comment by MikhailArkhipov** [comment]
fixed
