### ISSUE TITLE
View() doesn't support 2D vectors that aren't matrices

### ISSUE THREAD

**Issue by ebs238** [Microsoft/RTVS#3075]
RTVS silently produces no output View(x)  even though x can be coerced to a data.frame
this is related to Issue #3000 where View is identified as a workaround

source of Issue:
```
library(quantmod)
View(getSymbols("SPY", auto.assign = FALSE))
```

`tail(as.data.frame(getSymbols("SPY", auto.assign = FALSE)))`

produces:

```
           SPY.Open SPY.High SPY.Low SPY.Close SPY.Volume SPY.AdjFactor
2017-01-18   226.54   226.80  225.90    226.75   51146400             1
2017-01-19   226.84   227.00  225.41    225.91   65357500             1
2017-01-20   226.70   227.31  225.97    226.74  116431700             1
2017-01-23   226.74   226.81  225.27    226.15   72331900             1
2017-01-24   226.40   228.08  226.27    227.60   89144800             1
2017-01-25   228.70   229.57  228.51    229.57   80932500             1
```

Also, this works as expected:

`View(as.data.frame(getSymbols("SPY", auto.assign = FALSE)))`

**Comment by int19h** [comment]
`View` does not coerce to dataframe by design - it is a lossy operation on some types, and it creates a copy, which can be very expensive on large datasets. It will try to work directly on the original variable, using `[ ]` and `[[ ]]`. 

If you do want to specifically show something that isn't a dataframe as if it were one, you need to manually do the cast, i.e. `View(as.data.frame(getSymbols("SPY", auto.assign = FALSE)))`.

However, in this case, the returned value is a 2D vector of doubles, so `View` should display it in a grid just fine.

**Comment by int19h** [comment]
Hm, looks like we're specifically excluding vectors with dimensions for some reason - this is in `VectorView`:
```cs
        public override bool CanView(IRValueInfo evaluation) {
            if (evaluation != null && !evaluation.Classes.Any(t => _excludedClasses.Contains(t))) {
                return evaluation.Dim == null && evaluation.Length > 1;
            }
            return false;
        }
```
And then in `GridViewer`, we whitelist by classname, including `array` and `matrix`. But in this case we have a 2D vector that is *not* a matrix, so it doesn't apply either.

**Comment by ebs238** [comment]
but the docs on View say: 

> an R object which can be **coerced** to a data frame with non-zero numbers of rows and columns

also, MSR Client works as expected for:

`View(getSymbols("SPY", auto.assign = FALSE))`

**Comment by int19h** [comment]
The docs apply to the standard implementation of `View` from the standard library. RTVS replaces it with its own, to provide a custom viewer that opens data in a VS tab, and offer some other improvements (e.g. it virtualizes data access, so that you can view extremely large datasets). The side effect of those is that it doesn't have to coerce to dataframe to view the data (and coercing it would defeat the lazy data access).

However, we should still be showing the grid here. Generally speaking, anything that behaves like a 2D array - for which `dim()` returns two values, and which can be indexed with `[]` using two indices - should be supported. So that's definitely a bug!

**Comment by MikhailArkhipov** [comment]
I guess when `evaluation.Dim != null && evaluation.Dim.Count == 2` we should view it

**Comment by int19h** [comment]
I've looked at `VectorView`, and it does a bunch more things wrong. It doesn't even check if the input is a vector, for one thing (but instead it has a blacklist of "not vector" classes, which is not and cannot be complete).

What it should actually do is this:
```cs
        public override bool CanView(IRValueInfo evaluation) {
            return evaluation != null &&
                evaluation.IsAtomic() &&
                evaluation.Length > 1 &&
                (evaluation.Dim == null || evaluation.Dim.Count <= 2) &&
                !evaluation.Classes.Any(t => _excludedClasses.Contains(t));
        }
```

`IsAtomic` is true if and only if it's an atomic vector (non-atomic vectors are lists, and are handled by `ListViewer`). The rest checks for proper number of dimensions, and excludes classes. And as for classes, it should just be:
```cs
        private readonly static string[] _excludedClasses = new string[] { "factor" };
```
because the other three that are currently there aren't vectors to begin with, so `IsAtomic` will exclude them.

**Comment by int19h** [comment]
(note `<= 2` - we support 1D vectors in the grid, they're displayed in a single column, same as vectors with no dimensions at all)

**Comment by ebs238** [comment]
understood.. and i'm happy that my particular scenario will be fixed, 

In the grand scheme of things, if print() is too slow #3000, and View(as.data.frame(x)) is the only option, does it really matter if the coerce is called explicitly or implicitly? If it does, it seems that RTVS is changing the semantic contract of View, so maybe it would be good to add an explanatory error/warning that explicit coerce is needed.

**Comment by MikhailArkhipov** [comment]
1D is a different viewer, there is specialized class

**Comment by int19h** [comment]
That class is also wrong, it checks for things like `array`. And really it's unnecessary. Note that `Dims == null` is also 1D, it's just 1D that's not explicitly so. It doesn't make sense to have that handled along normal vectors, but explicit 1D handled by a different class.

**Comment by int19h** [comment]
To clarify, this:
`xs <- 1:10`
has `Dim == null`, while adding this:
`dim(xs) <- 10`
will make `Dim.Count == 1`. But in most other respects they aren't different. They certainly aren't different at all for the grid view.

**Comment by int19h** [comment]
@ebs238, yes, we definitely should document the difference with stock `View`. 

Note though that it doesn't have to be `View(as.data.frame(x))` once we fix this bug. `View(x)` will work also. Generally speaking, if there's any data input for which `View()` works in RGui, but doesn't work in RTVS, it's a bug. Our `View` is supposed to be more flexible than the stock, and must handle everything that stock can handle (and then some).

**Comment by Hong-Revo** [comment]
Piggybacking on this issue, since it's really about the same thing: viewing a data.frame object works, but viewing a tibble (Hadley Wickham's subclass of data frames) doesn't.

    df <- mtcars
    tib <- tibble::as_tibble(df)

Internally, a tibble is just a data frame with some extra classes tacked on:

    > class(tib)
    [1] "tbl_df"     "tbl"        "data.frame"

**Comment by int19h** [comment]
Could you file the `tibble` bug separately? I can repro, but the nature of the error is different - the R code that's responsible for fetching grid data seems to be returning an incorrect number of elements.
