### ISSUE TITLE
ggvis sample crashes on remote

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3119]
```
library(ggvis)

# Make data set with categorical x
mtc <- mtcars
mtc$cyl <- factor(mtc$cyl)
mtc %>% ggvis(~cyl, ~ mpg) %>% layer_boxplots()
# Set the width of the boxes to half the space between tick marks
mtc %>% ggvis(~cyl, ~ mpg) %>% layer_boxplots(width = 0.5)

# Continuous x: boxes fill width between data values
mtcars %>% ggvis(~cyl, ~ mpg) %>% layer_boxplots()
# Setting width=0.5 makes it 0.5 wide in the data space, which is 1/4 of the
# distance between data values in this particular case.
mtcars %>% ggvis(~cyl, ~ mpg) %>% layer_boxplots(width = 0.5)
```

The code opens browser in local R in the end. On remote session terminates.

**Comment by MikhailArkhipov** [comment]
We should look into this for 1.0

**Comment by int19h** [comment]
This is a problem with the remote URI service. What happens here is that when you run that `ggvis` command, it ultimately sends a `!WebBrowser` request from the host to open a file:// URL. However, the code (`WebServer.CreateWebServerAsync`) assumes that the URLs are always http:// or https://, and simply doesn't touch the scheme at all when it generates a corresponding local URL. So you end up with something like:

file://127.0.0.1:58122/C:/Users/int19/AppData/Local/Temp/RtmpILtB0L/viewhtml57ac17f32290/index.html

which crashes because `System.Uri` doesn't like file URIs with a server in them and throws.

**Comment by int19h** [comment]
Minfix to just fetch the remote file doesn't work, because plots generate a bunch of files (images etc), which the main HTML then references. If we only fetch HTML and open it locally, then all those other files are missing.

**Comment by MikhailArkhipov** [comment]
May be OK to say this is not supported in remote in 1.0 and open work item for the future to sort it out

**Comment by karthiknadig** [comment]
Is it possible to have R start a http server, at the file path? That way we could catch any "file://" !WebBrowser requests (on the RHost side) and have them directed towards the http server. Then actually send a "http://" !WebBrowser path of the newly created webserver.

**Comment by int19h** [comment]
I ran into some other design issues for a full fix that need further investigation, so let's just block this for remote for 1.0.
