### ISSUE TITLE
Message to reload autosave after reset is wrong

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#3120]
When you click Reset on REPL, it will prompt you to save.
Click Yes.
You will see a new session start, and then this other prompt appears:
```
---------------------------
Microsoft Visual Studio
---------------------------
Previous R session terminated unexpectedly, and its global workspace has been saved to image "~/.Autosave.RData". Would you like to reload it?
---------------------------
Yes   No   
---------------------------
```

It didn't really terminate **unexpectedly**.

Also, that first prompt when you reset, we probably want that an option to control whether we prompt or not.

**Comment by MikhailArkhipov** [comment]
@jflam we need PM input

**Comment by int19h** [comment]
Regarding the message, we should just fix it. The problem is that the code that reloads the session was written back when the only reason why it'd be saved in the first place is because the host was abruptly disconnected from. Now this is not the case anymore.

So we need some mechanism to provide a reason when saving state, such that it can be displayed on reload. For example, a .txt file next to .rdata, where the message could go. Then Reset would just write something like "R session was reset", and the code that detects and reloads saved session would check for that file, and use the message from it if it exists.

**Comment by karthiknadig** [comment]
Can't we just remove the word "unexpectedly"? rest of the stuff makes sense to me. "Previous R session terminated, and its global state was saved. Would you like to reload it?" This is correct in both reset and unexpected termination cases.

I agree that having a more accurate response, "R Session was reset, and its glob..." would be ideal.

**Comment by int19h** [comment]
That sounds reasonable, and is a much simpler fix.

**Comment by MikhailArkhipov** [comment]
I think issues here are

1. Add control over dialog that asks to save workspace to Tools | Options as we do for the session switching.
2. Since user initiated the reset - we should not be saving automatically and prompting to reload.

**Comment by int19h** [comment]
Ah, I see, so you think we should avoid the prompt after the reset altogether, since they already had one before the reset?

**Comment by jflam** [comment]
I'm in favor of the simpler solution of removing the _unexpectedly_ word. Let's see if folks are actually confused enough by this to file a bug.

**Comment by MikhailArkhipov** [comment]
It is annoying to see 3 (three) message box for the reset. We can add controllable suppression to the first one but we should really tell between R crash and the user-induced reset.

**Comment by smortaz** [comment]
+1
