### ISSUE TITLE
Connect from RTVS/master to remote on 1.0 throws exception

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3157]
```
R evaluation failed:

rtvs:::packages.installed.functions()

Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'packages.installed.functions' not found
Calls: ::: -> get
```

This must be handled and reported that local/remote and incompatible.

**Comment by AlexanderSher** [comment]
`packages.installed.functions` doesn't exist in 1.0, it was added in PR https://github.com/Microsoft/RTVS/pull/3089 and wasn't ported.
At this point, we have enough changes in `master` that make it incompatible with `Release/1_0`

**Comment by int19h** [comment]
We just need better error reporting for incompatibilities.

In the `rtvs` package in `util.R`, there is already a variable named `version`. It's currently set to 1. There's a check for the value of that variable in `RSession.LoadRtvsPackage`.

So we just need to update this number as needed to reflect breaking changes in the package.

**Comment by AlexanderSher** [comment]
So what is our version in master? 1.0.1?

**Comment by MikhailArkhipov** [comment]
Yes, I am aware of the change. The issue here is that remote may not be compatible and we can't just crash. We could update 1.0 short term but long term we need some way to handle breaking changes.

**Comment by MikhailArkhipov** [comment]
Let's say master is for VS 2017 and the version it TBD

**Comment by AlexanderSher** [comment]
After changing the `rtvsPackageVersion`, there is no any warning until user enters something in REPL. Not sure if it expected.

Generally speaking, any change in signature of any function in `rtvs` package or in IRCallback makes it incompatible with previous one. When we start the RHost, we already have its version in `AboutHost.Version`, so we probably should check for it before switching.

**Comment by AlexanderSher** [comment]
> long term we need some way to handle breaking changes

We can make RTVS load its package from client side instead of providing it as part of installation. That would help with package changes. With `IRCallback`, I think the only way is to provide different versions of the interface and make it as general as possible.

**Comment by AlexanderSher** [comment]
@int19h , @karthiknadig , can we use our blob API to upload package to the broker side and add it to the library?

**Comment by int19h** [comment]
Not all changes in signatures are necessarily incompatible - e.g. it's safe to add arguments if you provide default values for them. 

For `IRCallback`, as I recall, we wanted to get away from a fixed list of callbacks post-1.0, and just have a general-purpose registration mechanism in `RHost` for anything other than the absolutely fundamental callbacks (basically just the stuff that's needed for REPL proper).

Uploading the package doesn't fully solve the problem, because a lot of its functionality depends on R functions implemented in C and exported from the host - so there's also the question of package/host compatibility. However, the current design is also suboptimal - there's no particular reason why most of native functions have to be in the host, we just put them there because it was simpler than making a native package. But we could decouple the host proper (again, just the stuff that's needed for REPL and expression eval) from most everything else, and just export a stable ABI for low-level stuff like "send request" and "get response". Then all other native code could go into `rtvs`, and use that stable ABI from the host. I think even the graphics device / plots could be in that package.

**Comment by int19h** [comment]
BTW, one thing that would make this all a lot easier is making `rtvs` a proper package. Right now it isn't quite one, which is why you can't `library()` it. It's just a folder that corresponds to the layout of an unpacked package, which `loadNamespace` can load. 

If we make it a proper package, we could actually just upload the package file, and install it using normal means. 

However, making it a proper package would require building with R build tools. Meaning we'd need MinGW as a build dependency, and would need to integrade `R CMD BUILD` into our build system.

**Comment by MikhailArkhipov** [comment]
I don't think we can upload. There may be Remote 1.0, client 1.0 and client 1.1. Client 1.1 will break 1.0 by uploading 1.1 version

**Comment by MikhailArkhipov** [comment]
Unless you want to upload to a *specific host*

**Comment by int19h** [comment]
You mean, specific user?

In theory, we could actually maintain separate host binaries and packages for each user. Or even more than one per user, but then we'd need to add a parameter to specify the host/package combo to use when the session starts.

**Comment by AlexanderSher** [comment]
> Client 1.1 will break 1.0 by uploading 1.1 version

It can be uploaded in a separate folder and then accessed by providing `lib.loc`

**Comment by MikhailArkhipov** [comment]
Yeah but what about protocol changes when hosts becomes incompatible to the client see @int19h comment above

**Comment by int19h** [comment]
Protocol changes are a separate issue. We already have a protocol version number in the first packet.

What I was talking about is the interface between the host and the rtvs package. The package invokes a bunch of native functions inside the host via `.Internal(...)`. Occasionally, we add new functions to the host to enable new features in the package. Thus, these two also have to be in sync, or versioned in a way that retains compatibility.

We actually have several points where components interface and protocols can break:
1. Host <-> Client (with broker acting as pass-through). 
2. Package -> Host.
3. Client -> Package.
4. Client <-> Broker.

There will be one more in the future:

5. Host <-> Broker.

To implement things like session saving etc, broker needs to talk directly to the host sometimes, so it's no longer just a dumb pipe between host and client - it needs to know at least some message types.

**Comment by AlexanderSher** [comment]
But breaks 1,2 and 3 can be solved by uploading RHost.exe and package from the client side (if that version is missing on the broker side). We need to do it once for every version, then when user connects, we just pick the right folder.

**Comment by MikhailArkhipov** [comment]
Before we go into complete encompassing solutions... Short term: perhaps just code in the client acceptable versions of remote and then basically tell user that connection cannot be established. I'd expect organizations to have more or less consistent set of versions with proper rollouts of updates. 

So the issue is just tell user instead of crashing. Automatic handling and binaries/codes exchange can be considered in 2.0

**Comment by MikhailArkhipov** [comment]
For 1.0 I think we will re-fork master so 1.0 includes accessibility and becomes compatible with remote. But we still need to block incompatible. Maybe force versions to be equal and that's it.

**Comment by AlexanderSher** [comment]
I've added a `GetHostInformationAsync` call to the beginning of the `TrySwitchBrokerAsync`:

```cs
var hostVersion = (await brokerClient.GetHostInformationAsync<AboutHost>(cancellationToken)).Version;
var clientVersion = Assembly.GetExecutingAssembly().GetName().Version;
if (hostVersion.Major != clientVersion.Major || hostVersion.Minor != clientVersion.Minor) {
    return false;
}
```

**Comment by MikhailArkhipov** [comment]
You can borrow code from `SessionInformationCommand` and make it common. Message can be changed to 'incompatible'

```
            var localVersion = Assembly.GetExecutingAssembly().GetName().Version;
            if (localVersion.Major != 0 || localVersion.Minor != 0) { // Filter out debug builds
                string message = null;
                var serverVersion = new Version(aboutHost.Version.Major, aboutHost.Version.Minor);
                var clientVersion = new Version(localVersion.Major, localVersion.Minor);
                if (serverVersion > clientVersion) {
                    message = Resources.Warning_RemoteVersionHigher.FormatInvariant(aboutHost.Version, localVersion);
                } else if (serverVersion < clientVersion) {
                    message = Resources.Warning_RemoteVersionLower.FormatInvariant(aboutHost.Version, localVersion);
                }
                if (!string.IsNullOrEmpty(message)) {
                    sb.AppendLine(Environment.NewLine + message + Environment.NewLine);
                }
            }
```

**Comment by MikhailArkhipov** [comment]
BTW comparo should be `Version` to `Version`

**Comment by AlexanderSher** [comment]
Ok, thanks!
