### ISSUE TITLE
REPL output or input should be collapsible 

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3177]

**Comment by int19h** [comment]
To clarify, the idea is to have inputs and outputs show up as collapsible regions like in C#. This is particularly useful for outputs, because you can accidentally produce a really large output by doing something like `print(1:1000)`, and then you'll want to get it out of the way, but without clearing everything in the REPL. If the output for every prompt is separately collapsible, you can just collapse it down to one line.

**Comment by AlexanderSher** [comment]
Outputs are collected into one buffer, I'm not sure if it is possible to collapse them individually.

**Comment by int19h** [comment]
Isn't a C# document a single buffer with collapsible regions?

**Comment by MikhailArkhipov** [comment]
Collapsible regions do not work through projections. We do provide tagger for any R buffer, but editor ignores it if buffer is projected. Same happens to C# or JS inside HTML. This is basically core editor limitation.
