### ISSUE TITLE
Error loading R projects

### ISSUE THREAD

**Issue by Geof11061** [Microsoft/RTVS#3181]
2/12/2017 10:18:36 AM
Recoverable
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)
   at Microsoft.VisualStudio.R.Package.Shell.VsAppShell.EnsurePackageLoaded(Guid guidPackage)
   at Microsoft.VisualStudio.R.Package.ProjectSystem.RProjectLoadHooks.<InitializeProjectFromDiskAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.AutoLoadMethodStateMachine.<<StartExecution>b__6_0>d.MoveNext()

Unable to rectify this even with uninstall/reinstall.

**Comment by smortaz** [comment]
Hi. Sorry about that. Can you please do a

R Tools / feedback / send frown. And attach the logs so we can debug this?
Thank you

**Comment by Geof11061** [comment]
Hi - apologies, the functionality from the menu in Visual Studio that you mention doesn't seem to work (actually none of the options appear to do anything at all, maybe as a result of this problem).

In which directory on my machine might I find the logs that you require? 

Thanks!

**Comment by smortaz** [comment]
No problem. Do you know which version of visual studio and which version of
RTVS you are on?

**Comment by Geof11061** [comment]
Thanks - it is Visual Studio Community 2015, Version 14.0.25431.01 Update 3

R Tools for Visual Studio 0.5.21008.0800

Please let me know if you require anything else to help you - Thank you!

**Comment by AlexanderSher** [comment]
Can you please try to uninstall the extension, reset VS MEF Cache (delete %USERPROFILE%\AppData\Local\Microsoft\VisualStudio\14.0\ComponentModelCache folder) and then install it on the clean cache?

**Comment by Geof11061** [comment]
Thanks - I tried that (uninstall, delete cache folder, reinstall, start VS) but unfortunately this did not work, when trying to create a new R project after opening up VS again I get the error message "Invalid pointer (Exception from HRESULT:0x80004003 (E_POINTER)) - if I ignore this and then trying to open an existing project gives the same error message as my original post.

This extension did work fine and was able to write R code and use Variable Explorer etc. successfully for a few days but this started all of a sudden yesterday evening.

**Comment by DolanDack** [comment]
Actually, I face the exact same issue. 
And in fact I also I tried everything to solve the problem but still persists; @Geof11061 do you by any chance have Python Tools installed in your VS?
Because I was trying to deduce what component causes this error, so I completely uninstalled VS with all its components, then I did a clean install and started all over again, first installing R and slowly adding components. 
Up to the point where VS didn't contain Python Tools everything worked fine, but when I installed PT then the error occurred. 

An exception was encountered while constructing the content of this frame.  This information is also logged in "C:\Users\George\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml".
Exception details:
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.VisualStudio.Shell.Interop.IVsShell5.LoadPackageWithContext(Guid& packageGuid, Int32 reason, Guid& context)
at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.GetPackage()
at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()


Also here is a list of extensions:


Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586
Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA777
Visual Basic 2015   00322-80000-00000-AA777
Visual C# 2015   00322-80000-00000-AA777
Visual C++ 2015   00322-80000-00000-AA777
Application Insights Tools for Visual Studio Package   7.17.00119.9
ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.11107.0
ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
Azure App Service Tools v2.7.1   14.0.11112.0
Common Azure Tools   1.8
JavaScript Language Service   2.0
JavaScript Project System   2.0
Microsoft Azure Mobile Services Tools   1.4
NuGet Package Manager   3.4.4
NVIDIA CUDA 8.0 Wizards   8.0
NVIDIA Nsight Visual Studio Edition   5.2.0.16223
PreEmptive Analytics Visualizer   1.2
Python Tools for Visual Studio   2.2.50113.00
Python Tools for Visual Studio - Django Integration   2.2.50113.00
Python Tools for Visual Studio - Profiling Support   2.2.50113.00
R Tools for Visual Studio   0.5.21008.0800
SQL Server Analysis Services   13.0.1701.8
SQL Server Data Tools   14.0.61021.0
SQL Server Integration Services   
SQL Server Reporting Services   13.0.1701.8
TypeScript   1.8.36.0
Xamarin   4.2.1.62 (680125b)
Xamarin.Android   7.0.2.37 (ce955cc)
Xamarin.iOS   10.2.1.5 (44931ae)

**Comment by Geof11061** [comment]
Yes DolanDack - thanks for your input. I do indeed have Python tools also installed. I had assumed the problem was with R because I get the error loading R projects and cannot run any R inside Visual Studio any more, and yet I can still run Python. But it does sound like my scenario is identical to yours - a conflict between the two packages of some sort?

**Comment by DolanDack** [comment]
Yep, sure it is. If you leave Python and uninstall R then is fine, if you uninstall Python and you leave R, again is fine.
By the way, I have also installed VS 2015 Enterprise on a MacBook running Windows, I have R there too which was running smoothly as far as I remember (I use it rarely). Give me 5 mins to check if our problem occurs there too. If not I need to check what components I do not have installed on that machine.

**Comment by DolanDack** [comment]
Ok, so apparently on the Windows 10 system installed in the MacBook R Tools work fine, even alongside Python Tools. So, I am guessing that the problem might lie deeper, I have installed Tensorflow GPU (only on the desktop machine -- previous post) to work with python (that's why the NVIDIA CUDA in my previous post), have you by any chance done the same? I am trying to install tensorflow GPU + CUDA on the MacBook to see if I will experience the same problem. But generally, the whole thing looks really weird.

The list bellow is from the MacBook system:

Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01038
Installed Version: Enterprise

Architecture and Modeling Tools   00322-90150-00969-AA712
LightSwitch for Visual Studio 2015   00322-90150-00969-AA712
Microsoft Visual Studio Tools for Applications 2015   00322-90150-00969-AA712
Visual Basic 2015   00322-90150-00969-AA712
Visual C# 2015   00322-90150-00969-AA77
Visual C++ 2015   00322-90150-00969-AA712
Windows Phone SDK 8.0 - ENU   00322-90150-00969-AA712
Application Insights Tools for Visual Studio Package   7.0.20622.1
ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
Azure App Service Tools v2.8.2   14.0.20201.0
Common Azure Tools   1.8
DataFactoryProject   1.0
JavaScript Language Service   2.0
JavaScript Project System   2.0
Microsoft Azure Data Factory Node Node   1.0
Microsoft Azure HDInsight HQL Service   2.0.2900.0
Microsoft Azure HDInsight Tools for Visual Studio   2.0.2900.0
Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools
Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.40114.1
NuGet Package Manager   3.4.4
Office Developer Tools for Visual Studio 2015 ENU   14.0.23928
PreEmptive Analytics Visualizer   1.2
Python Tools for Visual Studio   2.2.50113.00
Python Tools for Visual Studio - Django Integration   2.2.50113.00
Python Tools for Visual Studio - Profiling Support   2.2.50113.00
R Tools for Visual Studio   0.5.21008.0800
SQL Server Analysis Services   13.0.1701.8
SQL Server Data Tools   14.0.61021.0
SQL Server Integration Services   
SQL Server Reporting Services   13.0.1701.8
TypeScript   1.8.36.0
Workflow Manager Tools 1.0   1.0

**Comment by DolanDack** [comment]
Ok I think I found were the error lies, 
so R (with MS R Open) + Python = works,
Python w/o R (with MS R Open) = works,
R Tools (with MS R Open) w/o Python = works,
R (with MS R Open) + Python + CUDA = works,
R (with MS R Open) + Python + Intel MKL Tools = doesn't work
I uninstalled Intel MKL Tools and again it works fine. Unfortunately though, I like the performance increase that MKL offers and I don't feel comfortable trading it for the convenience of having R in VS, no matter how much I like it as an idea.

**Comment by Geof11061** [comment]
Thanks DolanDack!

I don't have Intel MKL Tools I must say.. Also it is worth pointing out that I did have successful installation of both Python and R within Visual Studio that was working in tandem with each other for close to a week before it started going wrong. 

In the error message a posted originally, there is an assertion about a package not being loaded. Is there a debug version I can install that can give some idea as to what package is missing maybe?

**Comment by int19h** [comment]
@DolanDack, can you share the VS log file mentioned in the error message you posted earlier (C:\Users\George\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml)

@Geof11061, can you also take a look and see if you have one too? It should be in the same location, with the only difference being the user folder name.

It does, indeed, appear to be a package load issue, and that log file is where detailed errors about that are written.

**Comment by smortaz** [comment]
Hi - per Alex - can you also try 0.6?

download from here:  https://aka.ms/private-rtvs-ea-0-6

**Comment by Geof11061** [comment]
[ActivityLog.zip.zip](https://github.com/Microsoft/RTVS/files/769847/ActivityLog.zip.zip)

Hi int19h- hopefully you can see the log file I attached?

**Comment by AlexanderSher** [comment]
Hm... there is nothing about RTVS in the log. 
@Geof11061 , did you get the log after VS crashed? This file is created every time you start VS, so any errors from previous start are deleted.

**Comment by Geof11061** [comment]
Hi AlxanderSher - just reloaded the project and got the original error - this is the log at the time of the error 
[ActivityLog.zip](https://github.com/Microsoft/RTVS/files/769865/ActivityLog.zip)

**Comment by DolanDack** [comment]
Hey @AlexanderSher , I have attached the log-file from my system as you instructed. 
[ActivityLog.zip](https://github.com/Microsoft/RTVS/files/770739/ActivityLog.zip)

**Comment by DolanDack** [comment]
WoW! Guys, brilliant job @smortaz @AlexanderSher R works fine now, when I installed 0.6, with MKL too. Only a minor error, when I start VS and I have set the Data Science setting as a workspace format then I get an error (I have attached photo + log files) which is fixed if you reload the Data Science setting or bring up an interactive R window. Here is the new activity log zip in case you wish to compare them
[ActivityLog.zip](https://github.com/Microsoft/RTVS/files/770776/ActivityLog.zip)

**Comment by AlexanderSher** [comment]
Here is the stack trace from @DolanDack :
```cs
Object reference not set to an instance of an object.
   at Microsoft.R.Support.Settings.RToolsSettings.get_Current()
   at Microsoft.VisualStudio.R.Package.Repl.VsRInteractiveWorkflowProvider.CreateRInteractiveWorkflow()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.R.Package.Repl.VsRInteractiveWorkflowProvider.GetOrCreate()
   at Microsoft.VisualStudio.R.Package.Repl.Editor.KeyProcessorProvider.GetAssociatedProcessor(IWpfTextView wpfTextView)
   at Microsoft.VisualStudio.Text.Editor.Implementation.InputController.<UpdateKeyProcessors>b__8_0(IKeyProcessorProvider p)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)
```

**Comment by AlexanderSher** [comment]
@Geof11061 , have you tried 0.6 (https://aka.ms/private-rtvs-ea-0-6)?

**Comment by Geof11061** [comment]
@AlexanderSher - Hi Alexander, I have not had a chance yet to try 0.6 but I will do so tonight and let you know. Optimistic that it will based on the above.

**Comment by Geof11061** [comment]
Awesome - can confirm that the problem does not exist in version 0.6. Thanks!!!
