### ISSUE TITLE
View() does not show row names for ts and zoo

### ISSUE THREAD

**Issue by ebs238** [Microsoft/RTVS#3231]
View now support 2d data structures. ty very much. unfortunately, it does not show row names and instead just shows a row ordinal.  This is particularly horrible if the rownames contain useful information.

Example:
![capture](https://cloud.githubusercontent.com/assets/24379655/23244150/9401a0d4-f940-11e6-9f3f-c033ac5f9740.PNG)

**Comment by int19h** [comment]
The viewer does support row names:

![image](https://cloud.githubusercontent.com/assets/1175142/23244568/07ce6ebc-f93b-11e6-80e3-7bf82fe171c9.png)

The problem is that the data structure that is returned by `quantmod::getSymbols` doesn't actually have named rows in the usual meaning of the term - as in, it doesn't have `rownames()`:

![image](https://cloud.githubusercontent.com/assets/1175142/23244715/13f3a2ec-f93c-11e6-9306-26aa1ba022e1.png)

The reason why those names are printed out in the REPL, is because the `zoo` class customizes `print` to output that data.

It appears that the equivalent of `rownames` for `zoo` objects (of which this is an example) is the `zoo::index()` function. So far as I can tell, the reason why it uses it instead of `rownames` is to be able to associate values of types other than character with rows (since `rownames` is always a char vector).

 It looks like we could query `rownames(x)` first, and if that returns `NULL`, then try `format(zoo::index(x))` (handling the error if `zoo` package is not installed).

**Comment by MikhailArkhipov** [comment]
The change then sounds package specific... What about other packages that might be doing something similar?

**Comment by ebs238** [comment]
FYI, R open does seem to handle this
![capture](https://cloud.githubusercontent.com/assets/24379655/23270092/ff7e1602-f9af-11e6-9cf8-0342077180f4.PNG)

**Comment by int19h** [comment]
@MikhailArkhipov, it is indeed package specific, but the `zoo` package is [intended to be a generic package for indexed datasets](https://cran.r-project.org/web/packages/zoo/vignettes/zoo-design.pdf), for other domain-specific packages to build on. It's also very popular, especially if you count all the indirect uses by other packages (like `quantmod` in this example). So I think it would be reasonable for us to support it if it's installed.

**Comment by int19h** [comment]
@ebs238, thanks for pointing this out - I'll take a look at how it works there. One possibility is that they coerce the data to a `data.frame` before displaying - the object in question specializes this operation as well, and the resulting data frame does have named rows. Unfortunately, doing so also means that the entirety of the data is copied, which is infeasible on very large datasets; and it can cause name loss with other types.

**Comment by int19h** [comment]
Yep, they do use `as.data.frame`.

**Comment by jflam** [comment]
So ... what should we do in this case? I get that there is a copy operation involved here - should this be a configuration option that calls `as.data.frame` by default with an option to turn it off?

**Comment by int19h** [comment]
One of my comments above describes the solution in detail - we should just special-case `zoo::index` as an alternative to `rownames`. I think it's okay to special case it even though it's not a stock package, because it is a de facto standard package for anything that needs data other than strings associated with rows as "names".

**Comment by MikhailArkhipov** [comment]
OK, lets do it then.

**Comment by Neil-Schneider** [comment]
@MikhailArkhipov You asked for additional packages that might do something similar.

In addition to zoo, I would like to see View() updated for stat::ts. There are no row.names for `mts` and `ts` objects, but it is difficult to determine where you are in the time series when the calendar information is not shown in View(). 

I believe a quick solution would be to use `.preformat.ts()` for `ts` objects with `frequency` equal to 4 or 12.

```
ts.qtr = ts(c(1,2,3,4,5,6), start=2000, frequency = 4)
View(.preformat.ts(ts.qtr))

mts.qtr = ts(matrix(c(1,2,3,4,5,6), ncol=2), start=2000, frequency = 4)
View(.preformat.ts(mts.qtr))
```

Non-quarterly or monthly time series look nicer when not run through `.preformat.ts()`. It losses a nice column header.

**Comment by int19h** [comment]
It seems that there's a bunch of separate items here that pertain to time series.

In the code snippet above, `ts.qtr` is actually a dimensionless object. When `View()` is applied directly, it is therefore shown as a single column of values, with no names. This is the same behavior as in RStudio.

The pretty printer for it, however (the one that handles `print`) formats it as a table, but only for ts objects that have a frequency of 4 and 12:

```
> ts.qtr
     Qtr1 Qtr2 Qtr3 Qtr4
2000    1    2    3    4
2001    5    6        
```

This behavior appears to be hardcoded in the `.preformat.ts` function, which produces a matrix with the corresponding dimensions and rownames out of the time series.

For things that have a different frequency, however, the function doesn't do anything useful. The resulting matrix doesn't even have rownames corresponding to individual time points. Although this can be overridden by passing an explicit `calendar=TRUE` parameter to `.preformat.ts`.

The way `.preformat.ts` is implemented, it uses `time()` to compute time points for data in the time series, and then makes that the rownames of the generated matrix. We could do that as well. The question is whether we do it just for frequency=4 and frequency=12, or whether this should really be a separate configurable item in the grid (just for time series)? We could make a "calendar view" checkbox that toggles between the two modes.

Also, if calendar view is not used, we should still use `time()` to label rows. Effectively, for time series objects, `time()` is the logical equivalent of `names()`.

**Comment by Neil-Schneider** [comment]
Thanks for looking into this. I thought the `.preformat.ts` would make for a simple enhancement, butI did have a concern with `View()` representing the data as a matrix. While `mts.qtr` is also of class `matrix`, `ts.qtr` is not and representing it as a matrix through `View()` might be confusing. It might be better to keep the data as a vector with row names corresponding to the calendar.

**Comment by jflam** [comment]
Pinging this bug. I've been doing quite a bit of time series work with `zoo`, `tts`, and `quantmod`. Right now I need to get folks to use `head` instead of variable explorer / table viewer. We really do need to fix this.

**Comment by int19h** [comment]
The better workaround right now is to do `View(as.data.frame(...))`. This should get you the same behavior as RGui and RS (but at the cost of not having data virtualization). 

Let's do `time()` and `zoo::index()` support for row labels for Wave2, and skip the calendar stuff for now, since it's not clear whether it's a good thing or a bad thing (if we do it, it might get into the way of future features like editable grid).
