### ISSUE TITLE
R Tools Default Working Directory

### ISSUE THREAD

**Issue by tlong296** [Microsoft/RTVS#3232]
By default R Tools for Visual Studio sets the working directory to whatever ~ references. On a lot of machines whatever ~ references is not what is needed as the working directory in order to get RevoScaleR and MicrosoftML to work appropriately.

The work around for this is to not-so-obviously run the command setwd("c:\\users\\username"). This will solve any strange error you receive such as "file.exists(defaultDataDir) is not TRUE". It took me 3 weeks to figure out this error. The fact that the working directory has to be set to c:\users\username by default is still curious to me since R Client and its libraries do not live anywhere in that directory.

The underlying issue in R Tools is that you cannot change the default working directory. I find this really odd and almost unbelievable, like I've overlooked how to do this, but as I continue to look I cannot find a place to change the default working directory. 

This should be added to the tool. I prefer using R Studio right now for the sole reason that I don't have to run setwd(......) at the beginning of every session (Since it let me change the default working directory).

**Comment by MikhailArkhipov** [comment]
@AlexanderSher, @int19h  - do you think it is safe not to call `setwd(~)` ?

**Comment by int19h** [comment]
Working directory is a UX concept - we won't break any other code by not doing this.

But also, there was a reason why we decided to do it in the first place ... and presumably whatever scenario was behind it, it's still valid?

If I remember correctly, if we don't do `setwd` at all, it ends up being something really useless - some global directory where you don't have write access, and so cannot create files (I think it was R installation folder?)

It sounds like the fundamental issue here isn't that we always do `setwd`, but rather that we need to let users specify the target directory in options, rather than always assuming `~`.

**Comment by int19h** [comment]
At the same time, I'm curious why `~` did *not* resolve to the same thing as `c:\users\username`. That's where it's supposed to be...

**Comment by MikhailArkhipov** [comment]
I can make it optional with default to `off`. Thoughts?

**Comment by int19h** [comment]
Unless it's going to end up in the desired directory, I don't see how it solves the problem - @tlong296 will still have to manually do `setwd` to get there every time the session starts.

**Comment by MikhailArkhipov** [comment]
Yes, it would only control "don't change whatever is set in R by default"

**Comment by Hong-Revo** [comment]
I think I understand @tlong296 's issue. Most R code will translate `~` to your Documents folder, but RevoScaleR and MicrosoftML have some problems with it on Windows (since `~` is a Unix/Linux concept).

Regardless, setting the working dir to `~` is the default behaviour for rgui.exe if you start it from the provided shortcut. Otherwise, it will be set to, well, whatever directory you were in when you called it. If that was programmatically, I guess that would be either its own location, or that of the R.Host binary.

In addition to providing a way to change the default working dir, I'd suggest a couple of things:

* Calling `path.expand` in the RTVS startup will turn `~` into a real pathname:
```
> path.expand("~")
[1] "C:\\Users\\hongooi\\Documents"
```
* On the user side, creating a project will set the working dir to the project directory. In my experience, this saves having to do a manual `setwd` 99% of the time.

**Comment by tlong296** [comment]
Wow, I did not expect to have this many comments on this once I got back to work today.

int19h - yes, that is the fundamental issue. Users should be able to specify what the directory defaults to. You can do it in R Studio, R Studio is RTVS competition, and as far as I'm concerned this option is the only thing I like about it more that I have found. Also, the reason why ~ doesn't default to that directory for me is still unknown. Its a work environment with lots of network drives I'm connected to. Its defaulting to one of those for some reason. I'm sure theres a way to fix it on my end where ~ defaults to where it typically does, but I'd rather not go through that headache.

MikhailArkhipov  - If it was an option in RTVS it would just ideally need to be an option to be added under the R Tools tab of the toolbar under the working directory option. Ideally, I think in that option there should be a space that says default working directory. When you click that a window of some kind pops up that shows (~) since that is the default working directory. Then, the user can change that so it is loaded on startup.

**Comment by Hong-Revo** [comment]
> Also, the reason why ~ doesn't default to that directory for me is still unknown. Its a work environment with lots of network drives I'm connected to. Its defaulting to one of those for some reason. 

That would probably be due to your admin changing the location of your profile. Are these actual network drives (f:, n: etc) or network shares (\\machine\sharename)? R doesn't really like UNC paths. Sometimes they work, sometimes they don't.

**Comment by tlong296** [comment]
they are network shares \\machine\sharename

**Comment by MikhailArkhipov** [comment]
How's about

![image](https://cloud.githubusercontent.com/assets/12820357/23317659/3230ab12-fa84-11e6-9b41-c98fd5c2ddc5.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/a88219b7e2b759b4abf34f00e887c19d2439353f

**Comment by tlong296** [comment]
beautiful

**Comment by MironAtHome** [comment]
Didn't get this fix with checkin a88219b in my install 3 weeks ago, MSDN subscription, release 15.9.
Tried building using this Git repository and apparently build needs some tweaks. Just cloning repository and building Microsoft.R.Host.Client with a tweak using Visual Studio skips over building Microsoft.R.Host.Protocol and fails on dependencies.
It would be very nice if this is addressed somewhat expeditiously. Either VS needs to build software, so that it can be mended on the local machine using tweaked bits, or the install needs to be mended, so that it provides for the workaround with checkin a88219b.
Otherwise using your software presents a challenge that requires effort not so very different from other software, that does not really charge my company for MSDN subscription. And it does make difference, particularly when you have two kids and week - end.
All the best.
