### ISSUE TITLE
package did not load correctly

### ISSUE THREAD

**Issue by bertusavius** [Microsoft/RTVS#3257]
This issue is really bugging me:
Whenever I try to open a new R project in VS2015 i get an error message:
"The 'RPackage' package did not load correctly' 
The issue is rather similar to this thread:
http://stackoverflow.com/questions/17574089/microsoft-visual-studio-package-did-not-load-correctly

However I have tried out all suggestions mentioned within the thread and have not found a working solution. 
Can somebody help me out?

**Comment by AlexanderSher** [comment]
Can you please attach an ActivityLog.xml (%APPDATA%\Microsoft\VisualStudio\14.0\ActivityLog.xml) file? You'll have to change its extension to .txt or put it into .zip archive.

**Comment by bertusavius** [comment]
[ActivityLog.txt](https://github.com/Microsoft/RTVS/files/817142/ActivityLog.txt)

**Comment by AlexanderSher** [comment]
```
LegacySitePackage failed for package [RPackage]Source: 'System.ComponentModel.Composition' Description: No exports were found that match the constraint: 
	ContractName	Microsoft.VisualStudio.ProjectSystem.IProjectServiceAccessor
	RequiredTypeIdentity	Microsoft.VisualStudio.ProjectSystem.IProjectServiceAccessor
```

**Comment by MikhailArkhipov** [comment]
Try resetting MEF cache?

**Comment by AlexanderSher** [comment]
Also, can you please check if you have `Microsoft.VisualStudio.ProjectSystem.Implementation.dll` in the `%programfiles(x86)%\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\Project\` folder?

**Comment by bertusavius** [comment]
Thank you for the suggestion.
I cannot locate that file unfortunately. I don't even have the \Project folder

**Comment by MikhailArkhipov** [comment]
So no `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\Project` folder at all? Can you call `Help | About` in VS and then `Copy Info` and paste the result here? I am wondering what components are installed.

**Comment by bertusavius** [comment]
Microsoft Visual Studio 2015 Shell (Integrated)
Version 14.0.25420.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: IDE Standard

Microsoft Visual Studio Tools for Applications 2015   00322-10000-00000-AA747
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-10000-00000-AA747
Microsoft Visual Basic 2015

Visual C# 2015   00322-10000-00000-AA747
Microsoft Visual C# 2015

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

R Tools for Visual Studio   1.0.30228.1316 RC2
Provides project system, R Interactive window, plotting, and more for the R programming language.

SQL Server Analysis Services   13.0.1701.8
Microsoft SQL Server Analysis Services Designer 
Version 13.0.1701.8

SQL Server Data Tools   14.0.61021.0
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 13.0.1601.5

SQL Server Reporting Services   13.0.1701.8
Microsoft SQL Server Reporting Services Designers 
Version 13.0.1701.8

TypeScript   1.8.34.0
TypeScript tools for Visual Studio

**Comment by RafalLukawiecki** [comment]
Exactly the same issue here, all on a fresh new install of Windows 10. The Project directory mentioned above does not exist either. I hope there is a workaround.

**Comment by MikhailArkhipov** [comment]
It appears that this IDE is different from VS Community/Standard/Professional/Enterprise. Is this a VS-based application similar to, say, SQL Management Studio?

**Comment by MikhailArkhipov** [comment]
Basically VS IDE people said

"Integrated Shell d**oes not ship with any project systems**, so that would explain the missing folder. A work-around would be to download VS Community 2015, that will install on top of the current Integrated Shell."

**Comment by int19h** [comment]
IntShell is basically VS stripped down to bare bones.

IntShell doesn't have any project systems of the box, but it can have them added as components later. This happens if you install IntShell first, and then install other VS edition on top of it - the later install basically just adds a bunch of components into it. This one looks like IntShell with something installed on top of it, but I'm not sure what exactly. It's likely that it's still missing a bunch of packages that we rely on.

I would recommend fully uninstalling VS on that machine, and reinstalling VS Community (or other suitable edition) from scratch, to ensure that you have a good install with no bits missing. As it is, it's likely that some other bits might malfunction, and other extensions might not work.

**Comment by RafalLukawiecki** [comment]
I will test your suggestions today by reinstalling VS2015 Community. My current install's splash screen very clearly communicates that Visual Studio 2015 Community Edition is starting every time I launch it. In the Start menu it is also called Visual Studio 2015 Community Edition. There is *nothing* outwardly visible to say that the product installed is anything but Visual Studio 2015 Community Edition. However, it was installed already on the machine during the set-up of SQL Server 2016 Data Tools, which enable creation of Business Intelligence Projects, including SSAS, SSRS, and Data Mining, which I have been using for over 10 years. I also use SSMS, like, I supppose, all SQL Server users.

I would strongly suggest that you place an install-time check for this situation or to clearly communicate to the VS team to stop their product pretending to be something it claims it is but it is not. This is confusing even for a veteran user, and I suspect it turns off quite a few potential casual 1st timers. Microsoft R and SQL Server 2016 are tightly interwoven and marketed together as such, and it is only to be expected that this installation path is a common one.

Finally, all links that lead to the installation download page for VS 2015 CE actually land on VS 2017 CE which does not work with RTVS and confuses the situation further, and VS 2015 CE is rather hard to find now.

Many thanks for working on this, I can't wait for RTVS V1 to be out for me and my customers to enjoy.

**Comment by MikhailArkhipov** [comment]
@RafalLukawiecki  - can you please post Help | About from your VS here? 
Yes, we are looking to the blocker.

**Comment by RafalLukawiecki** [comment]
Dear Michael, downloading VS2015CE and installing it over generated an error but it went away after a reboot and I am pleased to say things are working again on this new machine. I found it, however, hard to find where to download VS2015CE from as all your links and anything on MSDN and other MS pages links to VS2017. Eventually I found an older link, using Google, that led me to a page in the MS download centre that still had VS2015CE. I would recommend hard-linking your page to wherever people are supposed to get VS2015CE from so that they do not give up. 😊

In the meantime I attach the System Report from Help/About, but I suspect it is all a bit too late, as I have already installed VS2015CE over the original set-up.

Thank you for being responsive, it is much appreciated.

Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Community

Microsoft Visual Studio Tools for Applications 2015   00322-20000-00000-AA059
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-20000-00000-AA059
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA059
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA059
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.0.20622.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.2.0.8
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.50113.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.50113.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.50113.00
Profiling support for Python projects.

R Tools for Visual Studio   1.0.30228.1316 RC2
Provides project system, R Interactive window, plotting, and more for the R programming language.

SQL Server Analysis Services   13.0.1701.8
Microsoft SQL Server Analysis Services Designer
Version 13.0.1701.8

SQL Server Data Tools   14.0.61021.0
Microsoft SQL Server Data Tools

SQL Server Integration Services
Microsoft SQL Server Integration Services Designer
Version 13.0.1601.5

SQL Server Reporting Services   13.0.1701.8
Microsoft SQL Server Reporting Services Designers
Version 13.0.1701.8

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

**Comment by int19h** [comment]
> it was installed already on the machine during the set-up of SQL Server 2016 Data Tools,

That would be how you've got IntShell first. So far as I remember, SQL Server Tools is IntShell + a bunch of SQL-related extensions. 

Thank you for clarifying this! We'll definitely look into it.

**Comment by CharlesOkwuagwu** [comment]
Please is this resolved?

**Comment by MikhailArkhipov** [comment]
If we are talking about VS 2015, it is no longer being updated. New RTVS versions (1.2, 1.3) are part of VS 2017 only. We don't have active package loading bugs there though.

For VS 2015 general recommendation is to add .NET Development (C#) to VS installation if you don't have one installed.

**Comment by CharlesOkwuagwu** [comment]
My issues is actually with the SQL Server Management Studio.
I Googled the errors i was getting and it brought me here.

I know SSMS uses some version of VS-IDE ... was hoking to find hints for a resolution... none so far

**Comment by MikhailArkhipov** [comment]
RTVS is not supported in SSMS, SQL Studio is minimal IDE and is missing a lot of required components. Such as project system, interactive window console just to mention a few.
