### ISSUE TITLE
R Tools for Visual Studio 2017

### ISSUE THREAD

**Issue by plr1975** [Microsoft/RTVS#3276]
Any ETA for VS 2017?

**Comment by smortaz** [comment]
Around may, with preview releases earlier.

**Comment by mvacha** [comment]
So, I assume rtvs is stuck on the same issues as Python (translations)?

**Comment by smortaz** [comment]
Yes. Localization and accessibility requirements.

**Comment by mvacha** [comment]
And do you plan to release rtvs as part of VS Preview? Python is already there, but no R :(

**Comment by smortaz** [comment]
Absolutely. We are shooting for April/May timeframe for RTVS for VS2017.
Python had already shipped inside the 2015 box so it got an exception.

**Comment by mvacha** [comment]
Wouldn't it be at least possible to release the package that shipped with VS 2017 RC1 (I think)?

**Comment by MikhailArkhipov** [comment]
We currently don't have installer. VS 2017 is installed very differently from 2015 so the existing MSI-based installer won't work. In in-box case we provide components and internal VS installer takes care of them. Also, VS installer is using new format which is not compatible with the Gallery (i.e. RTVS cannot be packaged as traditional style gallery extension). In order to make RTVS installable from outside VS we'd need to craft some sort of installer or script. Which would be error prone and when official version comes out it won't be able to upgrade in place, creating possible ugly bugs and crashes since two copies of the code may end up in VS.

**Comment by mvacha** [comment]
Ok, thanks for reply. I tried building the RTVS from sources for VS 2017, but failed everytime :( I assume I'll have to wait for the official release then. And thanks for doing good work on RTVS.

**Comment by MikhailArkhipov** [comment]
Depends which branch are you building. Release/1_0 is the stable one.

**Comment by mvacha** [comment]
Ok, so I managed to build it, but found few files missing from the repo. Probably just forgotten references, that are no longer used in project, fixed them in PR #3324 .

**Comment by AmrutaKar** [comment]
i installed all my outstanding updates for visual studio 2017 and it all worked after that
