### ISSUE TITLE
"Send to remote" on Project/dir only sends .R files

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3282]
In the Solution Explorer, when I right-click on a project or directory and choose Send to Remote, it only uploads R files. Should it instead send all files under that location?

I can send any individual file by right-clicking on it, so there don't seem to be any limitations on what can be sent.

**Comment by int19h** [comment]
Check out project properties (can be accessed by right-clicking the project node in Solution Explorer). There's a setting there that lets you define which files are affected by this command.

The reason why it doesn't just send everything is because you might want to avoid transmitting e.g. huge CSV datasets unnecessarily.

**Comment by Hong-Revo** [comment]
Ah, is this the "Run -> Transfer files on run" setting? Thanks.
