### ISSUE TITLE
Missing option to change R-engine/interpreter

### ISSUE THREAD

**Issue by th0ger** [Microsoft/RTVS#3285]
This [video](https://www.youtube.com/watch?v=KPS0ytrt9SA) from RTVS 0.3 explains how to change between CRAN, MRAN etc., using:
Options > R Tools > Advanced > General > R Engine (64-bit)

This option is not available in my fresh install (RTVS_2017-03-07.4.exe).
Where can I switch to MRAN? (I already install Microsoft R Open).

**Comment by smortaz** [comment]
RTVS for 2017 will be back in april/may time frame.

meanwhile, RC3 is available for 2015.

thanks.

**Comment by int19h** [comment]
I don't think this is about VS 2017. It's about a recent build of RTVS from 2017 :)

@th0ger, we have reworked handling of R implementations since 0.3 significantly. Now we try to detect all that you have installed, and show them all in the Workspaces tool window - you can show it via R Tools | Windows. There, you can easily switch between them, and manually add any missing ones that auto-detect didn't handle.

**Comment by MikhailArkhipov** [comment]
`R Tools -> Windows -> Workspaces`.
