### ISSUE TITLE
RTVS does not detect Microsoft R Client 3.3.2 correctly

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#3325]
Just installed it. The path should be: `C:\Program Files\Microsoft\R Client\R_SERVER`

But it is not auto-detected - the latest version is 3.2.2, which is the one that ships in SQL Server. 

![image](https://cloud.githubusercontent.com/assets/8877/24158935/fc703948-0e1a-11e7-94fb-4166359d9d10.png)

I recommend taking this bug before we ship.

**Comment by MikhailArkhipov** [comment]
This is because new version installs over old and does not remove old keys. So user ends up with 3.2.2 and 3.3.2 pointing to the same location and during de-duplication we pick the first one available which happens to be the lowest.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/cdaf1d80b7872869682e95778d267862582ee03c

**Comment by smortaz** [comment]
I'm still confused as to why RS doesn't have this problem

**Comment by int19h** [comment]
The problem in this case is basically the label. We do pick the right install, but we show it as 3.2.2, because registry has keys for R 3.2.2 *and* 3.3.2 (both pointing to the same folder, where R 3.3.2 is installed), and we were taking the first key we found.

RS doesn't have this problem because it doesn't have anything equivalent to the Workspaces window in the first place. It lets you work with one version at a time, configured in Options. And it doesn't try to give those versions descriptive labels - it just lists the folder paths as is.

**Comment by smortaz** [comment]
Ah ok. Thx.
