### ISSUE TITLE
setLocale fails on linux

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3387]
```
In Sys.setlocale("LC_CTYPE", ".437") :
 
 OS reports request to set locale to ".437" cannot be honored
```

**Comment by int19h** [comment]
Unsurprising, since 437 is a Windows codepage, which has no meaning on Linux. On MinGW, you can use codepages as encodings, but on Unix systems we have to use proper identifiers like `.UTF-8`.

**Comment by MikhailArkhipov** [comment]
We will be removing LC_CTYPE setting and rather replace it with setting environment variable `LANGUAGE=fr` since this is how R sets the locale in RGui.

**Comment by int19h** [comment]
`LC_CTYPE` does not have anything to do with UI language, it's about encoding.

**Comment by int19h** [comment]
But for Linux, we should just always set it to UTF-8 - it's strictly better than having any national encoding. We'd do it on Win32 if we could, but Windows (and hence MinGW) doesn't support UTF-8 as a codepage.

**Comment by MikhailArkhipov** [comment]
Yes, should be `UTF-8` on Linux, I just mean that R sets locale internally by looking into the env variable. We don't have to set `LC_*` explicitly.

**Comment by MikhailArkhipov** [comment]
Basically same as calling `Sys.setlocale('french')`

**Comment by int19h** [comment]
`LC_CTYPE` is also an environment variable actually. But they set different aspects of the locale. `LC_CTYPE` specifies classification (e.g. what's considered a letter) and encoding/conversion. `LANGUAGE` is the UI language (specifically, it's what gettext uses to look strings up) - it doesn't specify the encoding. But we do want to work with a specific encoding, so we need to set both of these separately.

**Comment by MikhailArkhipov** [comment]
I think if we just set the language. R will set encoding as per platform. I.e. utf-8 on Linux and appropriate codepage on Win32. Try `Sys.setlocale('russian')`, see what `Sys.getlocale()` reports.

**Comment by int19h** [comment]
To clarify, `LANGUAGE` is not actually part of the locale (as C/POSIX defines it) at all. It's a gettext-specific variable, and it can only be set to a language identifier like `en` or `en-US`. It does not include the encoding, and does not say anything about encodings. It also doesn't affect the `LC_*` categories in any way. 

In fact, per gettext own docs, the normal way of setting the language is via `LANG`, and `LANGUAGE` should only be used if you want to specify multiple fallback languages. Even then, you should still specify `LANG`, and `LANGUAGE` is in addition to that.

https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html

https://www.gnu.org/software/gettext/manual/html_node/The-LANGUAGE-variable.html

**Comment by int19h** [comment]
When you do `Sys.setlocale` without specifying the category, it is the same as specifying `LC_ALL` (i.e. setting all categories). It's not the same as `LANGUAGE`. Although, because it includes `LC_MESSAGES`, it should also change the UI language (but it looks like it doesn't quite do that on Windows, because MinGW doesn't support `LC_MESSAGES`; so we might need `LANGUAGE` for Windows specifically).

Note that you can still specify the encoding. The full format of the locale identifier includes it, e.g.: `en-US.UTF-8`. We currently skip the part before the dot, and *only* specify the encoding.

If we do skip the encoding, and only specify the language, then we get a locale that is sufficient for that language. But it does mean that we can e.g. get ASCII if we ask for en-US. A Linux system can have more than one encoding available for any given locale - e.g. `en-US.ASCII`, `en-US.ISO-8859-1` (Latin-1) and `en-US.UTF-8` can all be there at the same time. I don't believe there's any guarantee that it'll give us UTF-8 if we don't ask.

**Comment by MikhailArkhipov** [comment]
At least on windows it seems to be setting all per specified language. Here is RGui with `LANGUAGE=ru`

![image](https://cloud.githubusercontent.com/assets/12820357/24682628/85e3f374-194f-11e7-85d4-62fd9ce6f405.png)

I'll see what it does in Mac later today.

**Comment by MikhailArkhipov** [comment]
Speaking of remote we would need to set locale to the client so on French VS user will get French R locale.

**Comment by int19h** [comment]
Windows doesn't have POSIX locales, so it's whatever MinGW does to emulate them. Since Windows doesn't have the notion of multiple encodings per one language, this behavior makes sense there - there's always one and only one non-Unicode encoding corresponding to the selected language.

Yes, we will want to push the language selected on the client to the host side of things, so that R outputs in that language. There will be limitations, however. On Linux, there's no guaranteed predefined set of locales - there's at least one (C), but beyond that, it's whatever the system administrator has configured. So we can try to set it to `fr-FR.UTF-8`, for example - but we have to be prepared with the possibility that said locale is simply not installed on the system.

**Comment by MikhailArkhipov** [comment]
R converts Windows locales and language names to Unix in `dcigettext.c`. Comment says
```
  /* We use the settings in the following order:
     1. The value of the environment variable 'LANGUAGE'.  This is a GNU
        extension.  Its value can be a colon-separated list of locale names.
     2. The value of the environment variable 'LC_ALL', 'LC_xxx', or 'LANG'.
        More precisely, the first among these that is set to a non-empty value.
        This is how POSIX specifies it.  The value is a single locale name.
     3. A system-dependent preference list of languages.  Its value can be a
        colon-separated list of locale names.
     4. A system-dependent default locale name.
     This way:
       - System-dependent settings can be overridden by environment variables.
       - If the system provides both a list of languages and a default locale,
         the former is used.  */
```
