### ISSUE TITLE
default keyboard shortcut conflict

### ISSUE THREAD

**Issue by ebs238** [Microsoft/RTVS#3452]
Source R Script  `ctrl+shif + s` shortcut conflicts with with VS default `File > Save All`

**Comment by MikhailArkhipov** [comment]
By design. People prefer this since it is same as RStudio. It is possible to have same shortcuts as they are bound based on context. I.e. shortcut bound in context of editor wins over global when editor has focus. Ex. Ctrl+C means Copy in the editor but may mean 'Break' if window is similar to command line, for example.
