### ISSUE TITLE
Issue 3426 appears to be unresolved, erratic behaviour still perists

### ISSUE THREAD

**Issue by virusme** [Microsoft/RTVS#3569]
You could also add VS2015 & VS2017 Enterprise editions to the mix.

Please refer to the original issue for details: https://github.com/Microsoft/RTVS/issues/3426

I was unable to "re-open" the old issue, hence created a new one.

**Comment by MikhailArkhipov** [comment]
Is it exactly same case? Are you using 2017 or 2015? 2017 updates quite a bit slower since we have to join cumulative updates coming from multiple teams. It did not have same build as https://aka.ms/rtvs-current, 15.2 was on older beginning of April build. 

For 2017 you need 15.2.2 (26430.12) which was published 30th of May I believe.

**Comment by MikhailArkhipov** [comment]
Folding into #2091
