### ISSUE TITLE
Linux: Generate control file for the .deb package

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3631]
Control file has to be updated with the version number. Figure out a way to generate it as a part of the nightly builds:
```
Package: r-remote-svc
Version: 1.1.<build>.<rev>
Section: development
Priority: optional
Architecture: amd64
Depends: explain51, libzip4
Suggests: r-base (>= 3.2.0), microsoft-r-open-mro-3.2 (>=3.2.0)
Maintainer: rtvs
Description: <description>
```

**Comment by karthiknadig** [comment]
@int19h Any suggestion on how to generate this as a part of the nightly build?

**Comment by int19h** [comment]
Since we're using MSBuild to drive the overall build across all the projects, probably use that. Some options there:

- manually with `ReadLinesFromFile` and `WriteLinesToFile` tasks;
- `Exec` task to invoke e.g. [m4](http://mbreen.com/m4.html) to do preprocessing, and pass it the version number as a variable;
- `XslTransformation` task with `<xsl:output method="text">`.

**Comment by AlexanderSher** [comment]
We use MSBuild only to build. For nuget restore we use power shell. For git submodule sync, we use simple bat file. So I would've use whatever is simpler.

**Comment by karthiknadig** [comment]
On Linux build agent, we are using `dotnet restore` to do nuget restore and `dotnet msbuild` to build. The git module sync bat file does not work on linux, so i am doing that as cmd tasks.

**Comment by int19h** [comment]
This is not just for the build server - we'll also want to build the package locally for testing. And it's not a private artifact, so it should be in this repo. We already generate the version number for the binaries as part of the build proper, so it would make sense to create the .deb as part of it as well.
