### ISSUE TITLE
else block incorrectly indented with expanded braces on

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3646]
The opening brace after the `else` is indented even though it's on a new line:

![image](https://user-images.githubusercontent.com/11328890/27463704-95a4038e-580c-11e7-9deb-3a446fc700a7.png)

**Comment by MikhailArkhipov** [comment]
This is basically by design since in

```
if(foo) {
}
else {
}
```

`else` is dangling and hence <ENTER> after it is not considering it to be beginning of a block. As in RS

![image](https://user-images.githubusercontent.com/12820357/27657539-d5cd341e-5c01-11e7-9a73-1b3e8a333851.png)

If it is indeed in a outser block

```
{
    if (foo) {
} 
else <ENTER>{
}
    }
```

positions brace correctly.

Now, there is a problem that dangling `else` does not get squiggled consistently... Also, `ENTER` right after `else` behaves somewhat differently

```
{
    if (foo) {
} 
else<ENTER> {
}
    }
```

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/b02ae48aefaa08d94eb1d1c97d889d474f9ddecf
