### ISSUE TITLE
Live markdown should scroll rmd and preview.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3762]

**Comment by MikhailArkhipov** [comment]
Depends how do you want to scroll. Web Essentials have some live scrolling but it is easier there since text position generally visually matches position in the HTML DOM. Not so much with embedded rendered objects.

Another problem is when there is live sync scroll and user also scrolls manually the preview pane. When it syncs again, should we scroll back or respect user scroll? Or try and calculate effective offset keeping position somewhere around the user selection?

**Comment by karthiknadig** [comment]
I think the scrolling should be like the scrolling in diff viewers. The markdown side or the rendered side might have a large blocks,  similar to the diff left and right side. Ideally there should be the viewed region indicator or some other way to show the markdown region to rendered region mapping.
![image](https://user-images.githubusercontent.com/3840081/28680762-2909c604-72ac-11e7-8adf-363dd48f11d4.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/970cb420468cd69f0b6148d55a4847f8cd362731
