### ISSUE TITLE
Can't View .Last.value

### ISSUE THREAD

**Issue by mkoohafkan** [Microsoft/RTVS#3771]
The `View` command doesn't work with `.Last.value`. Simple example:

    data.frame(x = sample(1:100, 26), y = sample(LETTERS, 26))
    View(.Last.value)    # nothing happens

    data.frame(x = sample(1:100, 26), y = sample(LETTERS, 26))
    test = .Last.value
    View(test)
  
This problem also occurs with Piping:

    library(magrittr)
    test %>% View()    # nothing happens

**Version Info**

Visual Studio Professional 2015 v. 14.0.25431.01 Update 3
RTVS: 1.1.30627.1321

**SessionInfo**

R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.437    
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] colorspace_1.3-2 scales_0.4.1     compiler_3.4.1   lazyeval_0.2.0  
 [5] plyr_1.8.4       gtable_0.2.0     tibble_1.3.3     Rcpp_0.12.12    
 [9] ggplot2_2.2.1    grid_3.4.1       rtvs_1.0.0.0     rlang_0.1.1     
[13] munsell_0.4.3

**Comment by int19h** [comment]
I think `.Last.value` doesn't work, because `View()` itself changes its value (to `NULL`), and the grid dynamically tracks changes to the variable/expression it's opened for, and auto-refreshes itself.

The difference in observed behavior with RStudio seems to stem from the fact that RS only tracks changes done via explicit assignment, and so it doesn't notice the implicit change to `.Last.value` from every REPL eval, while RTVS tracks all changes, no matter how they're done.

**Comment by mkoohafkan** [comment]
This was observed in RGui (not RStudio) but I presume the underlying difference is the same. This is a a bit of a limitation with respect to piping `%>%` operations though, since it can be very helpful to `View` the results when constructing/debugging a dplyr chain without assigning a variable every time.

**Comment by int19h** [comment]
With `%>%`, it's a somewhat different issue. To make the grid window independent from the REPL (so that it doesn't block it), and to allow it to asynchronously load data while scrolling and to track changes, it needs to capture the whole expression passed to it, not just the value. You can find our R implementation for it in `rtvs` package, but it's pretty short, since the actual grid logic is elsewhere:
```r
view <- function(x, title) {
    if (is.function(x) || is.data.frame(x) || is.table(x) ||
        is.matrix(x) || is.list(x) || is.ts(x) || length(x) > 1) {

        dep <- deparse(substitute(x), backtick = TRUE)
        if (missing(title)) {
            title <- dep[1]
        }
        invisible(rtvs:::send_notification('!View', dep, title))
    } else {
        print(x)
    }
}
```
So all it really does is `deparse(substitute())` on the argument to get the expression, and then tells VS to open a grid for that expression. The grid then separately evals it to procure the value.

Now, the problem with `%>%` is that it basically sets a variable named `.`, and then invokes `View(.)`, and afterwards deletes the variable. From there it's the same problem as with `.Last.value` - by the time the grid loads (asynchronously), the expression it was loaded for is gone. 

RGui gets away with it because the grid effectively works on the copy of the data at the point it was invoked. However, that also makes their grid not reflect any changes. 

I don't think we can fix it for `View` in a transparent way without breaking functionality. But what we can do is provide an alternative function that behaves like RGui's `View`, basically taking a snapshot of data and working only with that. 

Another thing - if this is done specifically for the `%>%` scenario, what happens if you use `View` multiple times in a single pipeline expression? Would you prefer to see them all pop up at once (with the caveat that it will not be possible to tell which steps they correspond to, since the input expression for them is always `.`, and so the title will be that)? Or for the first grid to block execution until it is closed?

**Comment by mkoohafkan** [comment]
Oh, interesting. I wasn't aware that RTVS `View` would update the table as you continued to modify the variable.

Honesty, I'm not sure if I like the updating feature. Sometimes I like to `View` a variable prior to making changing so I have a snapshot of what it looked like before I started modifying it. Similarly, sometimes it is useful to `summarize %>% View` a variable  and use it for reference while working on the underlying table. But that's just my workflow, others may feel a dynamically updating `View` is more helpful.

You can't chain `View` using `%>%` since View returns NULL; however, you can use the magrittr `%T>%` pipe to spit out a View (or a plot) in the middle of a chain. In this case, `View`ing static snapshots of the variable from the middle of the chain is what makes `%T>`% valuable.

**Comment by mkoohafkan** [comment]
If you think it is valuable to implement a snapshot-based version of `View`, I wonder if it would be possible to make an IDE option (Tools --> options --> R Tools) to give uses the choice between dynamic and static `View`, rather than creating a new RTVS-specific function (which could reduce code portability).

**Comment by int19h** [comment]
It feels like both dynamic and snapshot behaviors could be useful for different scenarios within the same overall workflow, hence why I was thinking about a separate function. Although another way to do this would be to add another named argument to our version of `View`, so that you could do `View(x, snapshot = TRUE)` etc. So the default value would be propagated via options, but you'd still have the ability to override it when needed.

BTW, it occurred to me that `View` already allows you to set the title via `title=...`, and we do respect that; so if you wanted to set different titles to easily distinguish different steps in the pipeline, that's possible.

**Comment by mkoohafkan** [comment]
That sounds great---it would be extremely useful to be able to set the `snapshot` variable in the editor for occasions where you are writing code that needs to run on RGui or RStudio. 

Amazing I never checked the argument list to `View`. `title` argument is super helpful!

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/235d2372fc802648005bd71d2291feaf7c2f84f4
