### ISSUE TITLE
Connecting to linux shows this warning message.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3949]
```
In Sys.setlocale("LC_CTYPE", "en_US.UTF-8") :
  OS reports request to set locale to "en_US.UTF-8" cannot be honored
```
Looks like it only accepts Sys.setlocale("LC_CTYPE","C");

**Comment by MikhailArkhipov** [comment]
I thought R on *nix is always UTF-8.

**Comment by int19h** [comment]
Internally it does for strings etc, same as Windows. But when it interfaces with the OS, it uses the system locale (including locale encoding) - same as any other well-behaved Unix app.

We specifically invoke `Sys.setlocale`, IIRC, to make it talk the same language as the client, rather than the default locale on the server.

In this case, the problem is probably that locales weren't properly generated. The only locale that's always guaranteed to be there is "C", everything else is optional. Distros usually pregen the common ones by default, but it might be different with containers. Take a look at `locale-gen` and `/etc/locale.gen`.

**Comment by int19h** [comment]
Ah, apparently, on Debian/Ubuntu, you need to install the `locales` package - that'll bring in the pregened locales.

However, we should consider the possibility that locale for a given language might not be there. In this case we should fall back to `"C.UTF-8", so that we at least get proper encoding.

**Comment by karthiknadig** [comment]
Updated the images that we are testing to have the locales package. We have to handle this in code for customer scenarios.

**Comment by MikhailArkhipov** [comment]
I think it is done, correct?

**Comment by karthiknadig** [comment]
For someone in the future seeing this, not only do you have to install `locales` package. you also need to configure it:
```
sudo locale-gen "en_US.UTF-8"
sudo dpkg-reconfigure locales
```
