### ISSUE TITLE
[Feature Request] Syntax highlighting for functions and operators

### ISSUE THREAD

**Issue by mhmdmodan** [Microsoft/RTVS#4271]
RStudio has an optional feature to enable highlighting for functons, which offers a great increase in readability. Additionally, separate highlighting for operators, including custom binary operators (like the pipe %>%) would be quite helpful as well!

Here's a bit of code in RStudio:

![image](https://user-images.githubusercontent.com/7477482/35409274-53f18d24-01d7-11e8-89d4-87de2a4b47bd.png)

And the same with RTVS:

![image](https://user-images.githubusercontent.com/7477482/35409332-77bb0bfe-01d7-11e8-9eaf-88ea07cb327d.png)

Hopefully this can be implemented in future updates. Thank you!

**Comment by MikhailArkhipov** [comment]
VS has operator colors :-) It is just default is black. 

![image](https://user-images.githubusercontent.com/12820357/35411398-76bc3868-01cd-11e8-9ecc-f17a1f8f4991.png)

Function colors somewhat more difficult since it technically requires semantic analysis. However, simple approach would be to color anything that has following `(` (except keywords) as functions.

**Comment by mhmdmodan** [comment]
Ah! Thank you, didn't see that in the settings. I'm new to VS :)

As for the function call highlighting, looks like that's what RStudio does too.

![image](https://user-images.githubusercontent.com/7477482/35412243-2fc29678-01e1-11e8-91db-ad50c4fa75ae.png)

**Comment by MikhailArkhipov** [comment]
Not too complicated, but fairly extensive change. Classifier currently gets a single token while it needs to get token collection and the current token index so it can determine if this is a function.  Unfortunately, connection operations currently return elements and not indices. Also, tokenizer needs to run past the changed range since it needs to pick up the brace while it might be off-screen. Example

`func|(` <<- edge of the screen 

VS request for colors in the range would not include '(` since it is off screen. Tokenizer needs to picks few items beyond .the visual range then

**Comment by MikhailArkhipov** [comment]
@mhmdmodan  - which RStudio scheme it is? In the schemes I have I don't see option for function colors.

![image](https://user-images.githubusercontent.com/12820357/35583752-c6b0fb00-05a7-11e8-95b3-4bd671bccc3e.png)

**Comment by mhmdmodan** [comment]
@MikhailArkhipov - Hi, it must be enabled in the Code menu under the Display tab first.

![image](https://user-images.githubusercontent.com/7477482/35583995-32ab28ec-05b9-11e8-8a8b-797e9b0d4634.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/e83ab28203c1380dae8dbb739174cbc7efa70882

The color name is R Function. Default is black.
